import React, { useState } from 'react';
import { Download, X, Settings2, FileText, Type, Layout, Plus, Save, Upload, Cloud } from 'lucide-react';
import toast from 'react-hot-toast';
import { Button } from './ui/Button';
import { cn } from '../lib/utils';
import GenericCloudBackup from './GenericCloudBackup';

const PdfDownloadModal = ({ isOpen, onClose, initialSettings, onSave, isRoutineView = false }) => {
    const defaultSettings = {
        fileName: "week_routine",
        universityName: "North Western University",
        departmentName: "Department of Computer Science and Engineering",
        semesterName: "Spring 2026",
        additionalText: "",
        footerLeftText: "Generated by NWU Smart Routine System",
        footerRightText: "",
        permanentFacultyCols: 3,
        guestFacultyCols: 4,
        fontStyle: "helvetica",
        fontSize: 7,
        facultyFontSize: 7,
        headerFontSize: 16,
        bottomSignatures: [],
        headName: "Md. Mahedi Hasan",
        headDesignation: "Assistant Professor & Head",
        headDepartmentName: "Department of Computer Science and Engineering",
        headUniversityName: "North Western University, Khulna",
        signatureImage: null,
        signatureFontSize: 10,
        bottomSignaturesFontSize: 10,
        ccTitle: "C.C",
        ccText: ""
    };

    const [settings, setSettings] = useState(initialSettings || defaultSettings);
    const [activeTab, setActiveTab] = useState('settings');

    // Update internal state if initialSettings changes from outside
    React.useEffect(() => {
        if (initialSettings) {
            setSettings(initialSettings);
        }
    }, [initialSettings]);

    if (!isOpen) return null;

    const handleChange = (e) => {
        const { name, value, type } = e.target;
        setSettings(prev => ({
            ...prev,
            [name]: type === 'number' ? Number(value) : value
        }));
    };

    const handleSave = () => {
        onSave(settings);
        onClose();
    };

    const handleAddSignature = () => {
        setSettings(prev => ({
            ...prev,
            bottomSignatures: [...(prev.bottomSignatures || []), ""]
        }));
    };

    const handleRemoveSignature = (index) => {
        setSettings(prev => ({
            ...prev,
            bottomSignatures: (prev.bottomSignatures || []).filter((_, i) => i !== index)
        }));
    };

    const handleSignatureChange = (index, value) => {
        setSettings(prev => {
            const newSigs = [...(prev.bottomSignatures || [])];
            newSigs[index] = value;
            return { ...prev, bottomSignatures: newSigs };
        });
    };

    const handleImageUpload = (e) => {
        const file = e.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (event) => {
            const img = new Image();
            img.onload = () => {
                const canvas = document.createElement("canvas");
                canvas.width = img.width;
                canvas.height = img.height;
                const ctx = canvas.getContext("2d");
                ctx.drawImage(img, 0, 0);

                const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
                const data = imageData.data;

                // Make light pixels transparent to isolate the black/dark ink
                for (let i = 0; i < data.length; i += 4) {
                    const r = data[i];
                    const g = data[i + 1];
                    const b = data[i + 2];

                    // Simple threshold for light colors (can be tweaked)
                    if (r > 200 && g > 200 && b > 200) {
                        data[i + 3] = 0; // Alpha to 0 (transparent)
                    }
                }

                ctx.putImageData(imageData, 0, 0);
                const dataUrl = canvas.toDataURL("image/png");

                setSettings(prev => ({ ...prev, signatureImage: dataUrl }));
            };
            img.src = event.target.result;
        };
        reader.readAsDataURL(file);
    };

    const handleExport = () => {
        const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(settings, null, 2));
        const downloadAnchorNode = document.createElement('a');
        downloadAnchorNode.setAttribute("href", dataStr);
        downloadAnchorNode.setAttribute("download", `pdf_settings_backup_${new Date().toISOString().split('T')[0]}.json`);
        document.body.appendChild(downloadAnchorNode);
        downloadAnchorNode.click();
        downloadAnchorNode.remove();
        toast.success("PDF settings exported!");
    };

    const handleImport = (event) => {
        const file = event.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                const json = JSON.parse(e.target.result);
                // Basic validation
                if (json.universityName || json.fileName) {
                    setSettings({ ...defaultSettings, ...json });
                    toast.success("PDF settings loaded! Click 'Save' to apply.");
                } else {
                    toast.error("Invalid PDF settings file.");
                }
            } catch (err) {
                toast.error("Failed to read the backup file.");
            }
        };
        reader.readAsText(file);
        event.target.value = '';
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
            <div className="bg-card w-full max-w-lg rounded-xl shadow-xl border border-border overflow-hidden">
                <div className="flex justify-between items-center p-5 border-b border-border bg-muted/20">
                    <h3 className="text-xl font-bold flex items-center gap-2 text-foreground">
                        <Settings2 className="h-5 w-5 text-indigo-500" />
                        PDF Export Settings
                    </h3>
                    <Button variant="ghost" size="icon" onClick={onClose} className="hover:bg-destructive/10 hover:text-destructive transition-colors">
                        <X className="h-5 w-5" />
                    </Button>
                </div>

                <div className="flex bg-muted/30 p-1 border-b border-border">
                    <button
                        onClick={() => setActiveTab('settings')}
                        className={cn(
                            "flex-1 px-4 py-2 text-sm font-medium rounded-md transition-all",
                            activeTab === 'settings' ? "bg-card text-indigo-600 shadow-sm border border-border" : "text-muted-foreground hover:text-foreground"
                        )}
                    >
                        Layout Settings
                    </button>
                    <button
                        onClick={() => setActiveTab('cloud')}
                        className={cn(
                            "flex-1 px-4 py-2 text-sm font-medium rounded-md transition-all flex items-center justify-center gap-2",
                            activeTab === 'cloud' ? "bg-card text-indigo-600 shadow-sm border border-border" : "text-muted-foreground hover:text-foreground"
                        )}
                    >
                        <Cloud className="w-4 h-4" /> Cloud Storage
                    </button>
                </div>

                {activeTab === 'settings' && (
                <div className="p-6 space-y-6 max-h-[70vh] overflow-y-auto">

                    {/* Header Customization */}
                    <div className="space-y-4">
                        <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                            <Layout className="h-4 w-4" /> Header Content
                        </h4>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {!isRoutineView && (
                                <div>
                                    <label className="block text-sm font-medium mb-1.5 line-clamp-1">File Name</label>
                                    <div className="relative">
                                        <input
                                            type="text"
                                            name="fileName"
                                            value={settings.fileName}
                                            onChange={handleChange}
                                            placeholder="e.g. week_routine"
                                            className="w-full p-2.5 pr-12 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all placeholder:text-muted-foreground/50"
                                        />
                                        <span className="absolute right-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground pointer-events-none">
                                            .pdf
                                        </span>
                                    </div>
                                </div>
                            )}
                            <div className={isRoutineView ? "md:col-span-2" : ""}>
                                <label className="block text-sm font-medium mb-1.5 line-clamp-1">University / Organization Name</label>
                                <input
                                    type="text"
                                    name="universityName"
                                    value={settings.universityName}
                                    onChange={handleChange}
                                    placeholder="e.g. North Western University"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all placeholder:text-muted-foreground/50"
                                />
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                            <div>
                                <label className="block text-sm font-medium mb-1.5">Department Name</label>
                                <input
                                    type="text"
                                    name="departmentName"
                                    value={settings.departmentName}
                                    onChange={handleChange}
                                    placeholder="e.g. Dept. of CSE"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium mb-1.5">Semester Name</label>
                                <input
                                    type="text"
                                    name="semesterName"
                                    value={settings.semesterName}
                                    onChange={handleChange}
                                    placeholder="e.g. Spring 2026"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                        </div>

                        {!isRoutineView && (
                            <div className="mt-4">
                                <label className="block text-sm font-medium mb-1.5">Additional Top-Right Text</label>
                                <input
                                    type="text"
                                    name="additionalText"
                                    value={settings.additionalText}
                                    onChange={handleChange}
                                    placeholder="e.g. Version 2.0 (Optional)"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                        )}
                    </div>

                    {!isRoutineView && (
                        <>
                            <hr className="border-border" />

                            {/* Faculty Table Layout Customization */}
                            <div className="space-y-4">
                                <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                                    <Layout className="h-4 w-4" /> Faculty Table Layout
                                </h4>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-medium mb-1.5">Permanent Faculty Columns</label>
                                        <input
                                            type="number"
                                            name="permanentFacultyCols"
                                            value={settings.permanentFacultyCols}
                                            onChange={handleChange}
                                            min="1"
                                            max="6"
                                            className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                        />
                                        <p className="text-xs text-muted-foreground mt-1">Number of 3-item column triplets (Name, Form, Phone)</p>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium mb-1.5">Guest Faculty Columns</label>
                                        <input
                                            type="number"
                                            name="guestFacultyCols"
                                            value={settings.guestFacultyCols}
                                            onChange={handleChange}
                                            min="1"
                                            max="8"
                                            className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                        />
                                    </div>
                                </div>
                            </div>
                        </>
                    )}

                    <hr className="border-border" />

                    {/* Typography Customization */}
                    <div className="space-y-4">
                        <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                            <Type className="h-4 w-4" /> Typography
                        </h4>

                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                            <div className="col-span-2 md:col-span-1">
                                <label className="block text-sm font-medium mb-1.5">Font Style</label>
                                <select
                                    name="fontStyle"
                                    value={settings.fontStyle}
                                    onChange={handleChange}
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                >
                                    <option value="helvetica">Helvetica</option>
                                    <option value="times">Times New Roman</option>
                                    <option value="courier">Courier</option>
                                </select>
                            </div>
                            <div className="col-span-2 md:col-span-1">
                                <label className="block text-sm font-medium mb-1.5">Orientation</label>
                                <select
                                    name="orientation"
                                    value={settings.orientation || "l"}
                                    onChange={handleChange}
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                >
                                    <option value="l">Landscape</option>
                                    <option value="p">Portrait</option>
                                </select>
                            </div>
                            <div className="col-span-1">
                                <label className="block text-sm font-medium mb-1.5 line-clamp-1">Title Size</label>
                                <input
                                    type="number"
                                    name="headerFontSize"
                                    value={settings.headerFontSize}
                                    onChange={handleChange}
                                    min="10"
                                    max="36"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                            <div className="col-span-1">
                                <label className="block text-sm font-medium mb-1.5 line-clamp-1">Table Size</label>
                                <input
                                    type="number"
                                    name="fontSize"
                                    value={settings.fontSize}
                                    onChange={handleChange}
                                    min="4"
                                    max="14"
                                    step="0.5"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                            {!isRoutineView && (
                                <div className="col-span-2 md:col-span-1">
                                    <label className="block text-sm font-medium mb-1.5 line-clamp-1">Faculty Size</label>
                                    <input
                                        type="number"
                                        name="facultyFontSize"
                                        value={settings.facultyFontSize}
                                        onChange={handleChange}
                                        min="4"
                                        max="14"
                                        step="0.5"
                                        className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                    />
                                </div>
                            )}
                        </div>
                    </div>

                    {!isRoutineView && (
                        <>
                            <hr className="border-border" />

                            {/* C.C. Block Customization */}
                            <div className="space-y-4">
                                <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                                    <FileText className="h-4 w-4" /> C.C. List Section
                                </h4>
                                <p className="text-xs text-muted-foreground">Appears at the bottom left. Leave blank to hide.</p>

                                <div>
                                    <label className="block text-sm font-medium mb-1.5 line-clamp-1">Title</label>
                                    <input
                                        type="text"
                                        name="ccTitle"
                                        value={settings.ccTitle}
                                        onChange={handleChange}
                                        placeholder="e.g. C.C"
                                        className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-medium mb-1.5">List Items (Newline Separated)</label>
                                    <textarea
                                        name="ccText"
                                        value={settings.ccText}
                                        onChange={handleChange}
                                        rows={4}
                                        placeholder="1. Dean\n2. Registrar\n3. All CRs\n4. University Website"
                                        className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all resize-y"
                                    />
                                </div>
                            </div>
                        </>
                    )}

                    {!isRoutineView && (
                        <>
                            <hr className="border-border" />

                            {/* Head of Department Signature Customization */}
                            <div className="space-y-4">
                                <div className="flex items-center justify-between">
                                    <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                                        <FileText className="h-4 w-4" /> Head of Department Signature
                                    </h4>
                                    <div className="flex items-center gap-2">
                                        <label className="text-xs text-muted-foreground">Font Size:</label>
                                        <input
                                            type="number"
                                            name="signatureFontSize"
                                            value={settings.signatureFontSize}
                                            onChange={handleChange}
                                            min="6"
                                            max="24"
                                            step="0.5"
                                            className="w-16 p-1 text-xs rounded border border-input bg-background focus:ring-1 focus:ring-indigo-500 outline-none"
                                        />
                                    </div>
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-medium mb-1.5">Head Name</label>
                                        <input
                                            type="text"
                                            name="headName"
                                            value={settings.headName}
                                            onChange={handleChange}
                                            placeholder="e.g. Md. Mahedi Hasan"
                                            className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium mb-1.5">Designation</label>
                                        <input
                                            type="text"
                                            name="headDesignation"
                                            value={settings.headDesignation}
                                            onChange={handleChange}
                                            placeholder="e.g. Assistant Professor & Head"
                                            className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                        />
                                    </div>
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                                    <div>
                                        <label className="block text-sm font-medium mb-1.5">Department Name (Signature Block)</label>
                                        <input
                                            type="text"
                                            name="headDepartmentName"
                                            value={settings.headDepartmentName}
                                            onChange={handleChange}
                                            placeholder="e.g. Dept. of CSE"
                                            className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium mb-1.5">University Name (Signature Block)</label>
                                        <input
                                            type="text"
                                            name="headUniversityName"
                                            value={settings.headUniversityName}
                                            onChange={handleChange}
                                            placeholder="e.g. North Western University"
                                            className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                        />
                                    </div>
                                </div>

                                <div className="mt-4">
                                    <label className="block text-sm font-medium mb-1.5">Signature Image Upload (Captures Black Ink)</label>
                                    <div className="flex items-center gap-4">
                                        <input
                                            type="file"
                                            accept="image/*"
                                            onChange={handleImageUpload}
                                            className="block w-full text-sm text-foreground file:mr-4 file:py-2.5 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100 transition-all border border-input rounded-lg bg-background"
                                        />
                                        {settings.signatureImage && (
                                            <div className="h-10 w-24 bg-white border border-border rounded flex items-center justify-center overflow-hidden shrink-0">
                                                <img src={settings.signatureImage} alt="Signature Preview" className="max-h-full max-w-full object-contain" />
                                            </div>
                                        )}
                                    </div>
                                    <p className="text-xs text-muted-foreground mt-2">Upload a picture of the signature. The system will automatically remove the white background.</p>
                                </div>
                            </div>
                        </>
                    )}

                    <hr className="border-border" />

                    {/* Bottom Text Fields Customization */}
                    <div className="space-y-4">
                        <div className="flex items-center justify-between">
                            <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                                <FileText className="h-4 w-4" /> Bottom Text Fields
                            </h4>
                            <div className="flex items-center gap-2">
                                <label className="text-xs text-muted-foreground">Font Size:</label>
                                <input
                                    type="number"
                                    name="bottomSignaturesFontSize"
                                    value={settings.bottomSignaturesFontSize}
                                    onChange={handleChange}
                                    min="6"
                                    max="24"
                                    step="0.5"
                                    className="w-16 p-1 text-xs rounded border border-input bg-background focus:ring-1 focus:ring-indigo-500 outline-none"
                                />
                                <Button type="button" variant="outline" size="sm" onClick={handleAddSignature} className="h-7 text-xs ml-2">
                                    <Plus className="h-3 w-3 mr-1" /> Add Field
                                </Button>
                            </div>
                        </div>

                        <div className="space-y-2">
                            {(settings.bottomSignatures || []).map((sig, index) => (
                                <div key={index} className="flex items-center gap-2">
                                    <input
                                        type="text"
                                        value={sig}
                                        onChange={(e) => handleSignatureChange(index, e.target.value)}
                                        placeholder={`Text Field ${index + 1} (e.g. Prepared By...)`}
                                        className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                    />
                                    <Button type="button" variant="ghost" size="icon" onClick={() => handleRemoveSignature(index)} className="text-destructive hover:bg-destructive/10 shrink-0">
                                        <X className="h-4 w-4" />
                                    </Button>
                                </div>
                            ))}
                            {(!settings.bottomSignatures || settings.bottomSignatures.length === 0) && (
                                <p className="text-sm text-muted-foreground text-center py-2">No custom text fields added. Click 'Add Field' to create one.</p>
                            )}
                        </div>
                    </div>

                    <hr className="border-border" />

                    {/* Footer Customization */}
                    <div className="space-y-4">
                        <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                            <FileText className="h-4 w-4" /> Footer Layout
                        </h4>
                        <p className="text-xs text-muted-foreground">The center footer is reserved for automatic Page Pagination (e.g. "Page 1 of 4").</p>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-medium mb-1.5">Bottom Left Text</label>
                                <input
                                    type="text"
                                    name="footerLeftText"
                                    value={settings.footerLeftText}
                                    onChange={handleChange}
                                    placeholder="e.g. Generated by System"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium mb-1.5">Bottom Right Text</label>
                                <input
                                    type="text"
                                    name="footerRightText"
                                    value={settings.footerRightText}
                                    onChange={handleChange}
                                    placeholder="e.g. Confidential"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                        </div>
                    </div>

                </div>
                )}

                {activeTab === 'cloud' && (
                    <div className="p-6 max-h-[70vh] overflow-y-auto">
                        <GenericCloudBackup 
                            type="pdf_settings"
                            title="PDF Settings Backups"
                            description="Save your exact PDF export configurations to the cloud and restore them anytime."
                            onBackupDataGenerate={async () => settings}
                            onRestoreDataApply={async (json) => {
                                if (json.universityName || json.fileName) {
                                    setSettings({ ...defaultSettings, ...json });
                                } else {
                                    throw new Error("Invalid PDF settings file format.");
                                }
                            }}
                        />
                    </div>
                )}

                <div className="flex flex-wrap justify-between items-center gap-3 p-5 border-t border-border bg-muted/10">
                    <div className="flex items-center gap-2">
                        <Button variant="ghost" size="sm" onClick={handleExport} className="text-muted-foreground hover:text-indigo-600 px-2 h-8">
                            <Download className="h-3.5 w-3.5 mr-1.5" /> Backup
                        </Button>
                        <div className="relative">
                            <Button variant="ghost" size="sm" onClick={() => document.getElementById('pdf-restore-input').click()} className="text-muted-foreground hover:text-emerald-600 px-2 h-8">
                                <Upload className="h-3.5 w-3.5 mr-1.5" /> Restore
                            </Button>
                            <input
                                id="pdf-restore-input"
                                type="file"
                                accept=".json"
                                className="hidden"
                                onChange={handleImport}
                            />
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                        <Button variant="outline" onClick={onClose} className="px-5">
                            Cancel
                        </Button>
                        <Button onClick={handleSave} className="px-6 bg-indigo-600 hover:bg-indigo-700 text-white shadow-md">
                            <Save className="mr-2 h-4 w-4" />
                            Save Settings
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default PdfDownloadModal;
