import React, { useState, useEffect, useRef } from 'react';
import { getRoutine, addRoutineEntry, updateRoutineEntry, deleteRoutineEntry, clearRoutine, getRooms, getFaculty, getBatches, getCourses, updateBatch, getSettings, updateSettings } from '../services/api';
import { generateRoutineViewPDF } from '../utils/pdfGenerator';
import autoTable from 'jspdf-autotable';
import { Download, Plus, Filter, Calendar, Settings, X, Check, Trash2, Edit2, MapPin, Search } from 'lucide-react';
import { Button } from './ui/Button';
import { Select } from './ui/Select';
import { SearchableSelect } from './ui/SearchableSelect';
import { Card, CardContent } from './ui/Card';
import toast from 'react-hot-toast';
import { cn } from '../lib/utils';
import SettingsModal from './SettingsModal';
import PdfDownloadModal from './PdfDownloadModal';
import { useAuth } from '../contexts/AuthContext';
import FacultyContactModal from './ui/FacultyContactModal';

const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const operatingDays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

const RoutineView = ({ overtimeVisibility, setOvertimeVisibility }) => {
    const { user, hasPermission } = useAuth();
    const canEdit = hasPermission('edit_routine');

    // Scroll Sync Refs & State
    const tableContainerRef = useRef(null);
    const topScrollContainerRef = useRef(null);
    const duplicateHeaderRef = useRef(null);
    const [tableWidth, setTableWidth] = React.useState(0);
    const [showStickyHeader, setShowStickyHeader] = React.useState(false);
    const [headerLayout, setHeaderLayout] = React.useState({ left: 0, width: 0 });

    const getDefaultDay = () => {
        const now = new Date();
        const hour = now.getHours();
        const dayIndex = now.getDay(); // 0 is Sunday, 1 is Monday, ..., 6 is Saturday
        
        let targetDayIndex = dayIndex;
        
        // If it's after 5 PM (17:00), we look for the next day
        if (hour >= 17) {
            targetDayIndex = (dayIndex + 1) % 7;
        }

        let dayName = days[targetDayIndex];

        // If today/target day is Sunday, default to Monday
        if (dayName === "Sunday") {
            return "Monday";
        }

        return dayName;
    };

    const [routine, setRoutine] = useState([]);
    const [metadata, setMetadata] = useState({ rooms: [], faculty: [], batches: [], courses: [] });
    const [loading, setLoading] = useState(true);
    const [selectedDay, setSelectedDay] = useState(getDefaultDay());
    const [viewMode, setViewMode] = useState('master'); // 'master', 'section', 'batch', 'faculty'
    const [selectedBatchId, setSelectedBatchId] = useState(''); // For Section View
    const [selectedFacultyId, setSelectedFacultyId] = useState(''); // For Faculty View

    // Initialize state based on user role
    useEffect(() => {
        if (user) {
            if (user.role === 'Faculty' && user.facultyId) {
                setViewMode('faculty');
                setSelectedFacultyId(user.facultyId.toString());
            } else if (['Student', 'CR/ACR'].includes(user.role) && user.section) {
                setViewMode('section');
                setSelectedBatchId(user.section.toString());
            }
        }
    }, [user]);

    // Removed local overtimeVisibility state, now using props

    // Modal State (Unified for Add/Edit)
    const [showModal, setShowModal] = useState(false);
    const [editingId, setEditingId] = useState(null); // For Class Entry

    // Batch Room Editing State
    const [editingBatchId, setEditingBatchId] = useState(null);
    const [selectedBatchRoom, setSelectedBatchRoom] = useState(''); // If null, adding new class. If set, editing this ID.

    const [formData, setFormData] = useState({
        day: 'Monday',
        time: '08:00-09:15',
        batch_id: '',
        course_id: '',
        faculty_id: '',
        room_id: ''
    });

    // Multi-Class Selection Modal State
    const [selectionModalData, setSelectionModalData] = useState(null); // { classes: [], batchId: '' }

    // Settings State
    const [showSettingsModal, setShowSettingsModal] = useState(false);
    const [isPdfModalOpen, setIsPdfModalOpen] = useState(false);
    const [scheduleSettings, setScheduleSettings] = useState({
        general: { theory_slots: [], lab_slots: [], slot_mapping: {} },
        daily_overrides: {}
    });

    // Faculty contact modal state
    const [showContactModal, setShowContactModal] = useState(false);
    const [selectedFacultyList, setSelectedFacultyList] = useState([]);

    const defaultPdfSettings = {
        universityName: "North Western University",
        semesterName: "Spring 2026",
        departmentName: "Department of Computer Science and Engineering",
        footerLeftText: "Generated by NWU Smart Routine System",
        footerRightText: "",
        fontStyle: "helvetica",
        fontSize: 7,
        headerFontSize: 16,
        orientation: "l"
    };

    // Load initial PDF settings in fetchData
    const [pdfSettings, setPdfSettings] = useState(defaultPdfSettings);

    const handleSavePdfSettings = async (newSettings) => {
        setPdfSettings(newSettings);
        try {
            await updateSettings(newSettings, 'pdf_settings_routine');
            toast.success("PDF settings saved globally!");
        } catch (error) {
            console.error("Failed to save PDF settings", error);
            toast.error("Failed to save PDF settings to server. Saving locally only.");
            localStorage.setItem('nwu_routine_view_pdf_settings', JSON.stringify(newSettings));
        }
    };

    // Sync scroll position
    useEffect(() => {
        const table = tableContainerRef.current;
        const top = topScrollContainerRef.current;

        if (!table || !top) return;

        const handleTableScroll = () => {
            if (topScrollContainerRef.current && tableContainerRef.current) {
                const scrollLeft = tableContainerRef.current.scrollLeft;
                if (Math.abs(topScrollContainerRef.current.scrollLeft - scrollLeft) > 1) {
                    topScrollContainerRef.current.scrollLeft = scrollLeft;
                }
                if (duplicateHeaderRef.current && Math.abs(duplicateHeaderRef.current.scrollLeft - scrollLeft) > 1) {
                    duplicateHeaderRef.current.scrollLeft = scrollLeft;
                }
            }
        };

        const handleTopScroll = () => {
            if (tableContainerRef.current && topScrollContainerRef.current) {
                const scrollLeft = topScrollContainerRef.current.scrollLeft;
                if (Math.abs(tableContainerRef.current.scrollLeft - scrollLeft) > 1) {
                    tableContainerRef.current.scrollLeft = scrollLeft;
                }
                if (duplicateHeaderRef.current && Math.abs(duplicateHeaderRef.current.scrollLeft - scrollLeft) > 1) {
                    duplicateHeaderRef.current.scrollLeft = scrollLeft;
                }
            }
        };

        table.addEventListener('scroll', handleTableScroll);
        top.addEventListener('scroll', handleTopScroll);

        return () => {
            table.removeEventListener('scroll', handleTableScroll);
            top.removeEventListener('scroll', handleTopScroll);
        };
    }, []);

    // Effect for duplicate header scrolling and syncing widths
    useEffect(() => {
        const dup = duplicateHeaderRef.current;
        const table = tableContainerRef.current;
        const top = topScrollContainerRef.current;

        const handleDupScroll = () => {
             if (!dup) return;
             const scrollLeft = dup.scrollLeft;
             if (table && Math.abs(table.scrollLeft - scrollLeft) > 1) table.scrollLeft = scrollLeft;
             if (top && Math.abs(top.scrollLeft - scrollLeft) > 1) top.scrollLeft = scrollLeft;
        };

        if (dup) {
            dup.addEventListener('scroll', handleDupScroll);
            if (table) dup.scrollLeft = table.scrollLeft;
        }

        // Sync widths of columns
        if (showStickyHeader && dup && table) {
            const originalThs = table.querySelectorAll('thead th');
            const duplicateThs = dup.querySelectorAll('thead th');
            if (originalThs.length === duplicateThs.length) {
                for (let i = 0; i < originalThs.length; i++) {
                    duplicateThs[i].style.minWidth = `${originalThs[i].offsetWidth}px`;
                    duplicateThs[i].style.width = `${originalThs[i].offsetWidth}px`;
                }
            }
        }

        return () => {
            if (dup) dup.removeEventListener('scroll', handleDupScroll);
        };
    }, [showStickyHeader, tableWidth, routine, overtimeVisibility, selectedDay, viewMode]);

    // Track window scroll for sticky header visibility
    useEffect(() => {
        const handleWindowScroll = () => {
            if (tableContainerRef.current) {
                const rect = tableContainerRef.current.getBoundingClientRect();
                // 64px is navbar height. Support intersection below.
                if (rect.top <= 64 && rect.bottom > 150) {
                    setShowStickyHeader(true);
                    setHeaderLayout({ left: rect.left, width: rect.width });
                } else {
                    setShowStickyHeader(false);
                }
            }
        };

        window.addEventListener('scroll', handleWindowScroll);
        window.addEventListener('resize', handleWindowScroll);
        handleWindowScroll(); // Initialize checking

        return () => {
            window.removeEventListener('scroll', handleWindowScroll);
            window.removeEventListener('resize', handleWindowScroll);
        };
    }, []);

    useEffect(() => {
        fetchData();
    }, []);

    const fetchData = async () => {
        try {
            const [routineRes, roomsRes, facultyRes, batchesRes, coursesRes, settingsRes, pdfSettingsRes] = await Promise.all([
                getRoutine(),
                getRooms(),
                getFaculty(),
                getBatches(),
                getCourses(),
                getSettings('app_settings'),
                getSettings('pdf_settings_routine')
            ]);
            setRoutine(routineRes.data);
            setMetadata({
                rooms: roomsRes.data,
                faculty: facultyRes.data,
                batches: batchesRes.data,
                courses: coursesRes.data
            });
            if (settingsRes.data.success) {
                const settingsData = settingsRes.data.data;
                setScheduleSettings(settingsData);
                // Update form default if theory slots available in general config
                if (settingsData.general?.theory_slots?.length > 0) {
                    setFormData(prev => ({ ...prev, time: settingsData.general.theory_slots[0] }));
                }
            }
            if (pdfSettingsRes.data.success && Object.keys(pdfSettingsRes.data.data).length > 0) {
                setPdfSettings(pdfSettingsRes.data.data);
            }
            setLoading(false);
        } catch (err) {
            console.error(err);
            setLoading(false);
        }
    };
    
    const sortedBatches = React.useMemo(() => {
        if (!metadata.batches) return [];
        return [...metadata.batches].sort((a, b) => {
            const getSortMetadata = (name) => {
                const safeName = name || '';
                const parts = safeName.split(' ');
                const yearNum = parseInt(parts[0]) || 0;
                const semNum = parts.length >= 3 ? parseInt(parts[2]) : 0;
                return { year: yearNum, sem: semNum };
            };
            const metaA = getSortMetadata(a.name);
            const metaB = getSortMetadata(b.name);
            if (metaA.year !== metaB.year) return metaA.year - metaB.year;
            if (metaA.sem !== metaB.sem) return metaA.sem - metaB.sem;
            return (a.section || '').localeCompare(b.section || '');
        });
    }, [metadata.batches]);

    // Sync table width to scrollbars
    useEffect(() => {
        const updateWidth = () => {
            if (tableContainerRef.current) {
                setTableWidth(tableContainerRef.current.scrollWidth);
            }
        };

        updateWidth();
        const timer = setTimeout(updateWidth, 100);

        window.addEventListener('resize', updateWidth);
        return () => {
            clearTimeout(timer);
            window.removeEventListener('resize', updateWidth);
        };
    }, [routine, metadata, overtimeVisibility, loading, selectedDay, viewMode]);



    const resetForm = () => {
        setFormData({
            day: selectedDay, // Default to currently viewed day
            time: scheduleSettings.general?.theory_slots?.[0] || '08:00-09:15',
            batch_id: '', // Reset
            course_id: '',
            faculty_id: '',
            room_id: ''
        });
        setEditingId(null);
    };

    const openAddModal = (overrides = {}) => {
        resetForm();
        if (overrides.batch_id || overrides.time) {
            setFormData(prev => ({ ...prev, ...overrides }));
        }
        setShowModal(true);
    };

    const openEditModal = (classData) => {
        // Handle array (multiple classes in one slot)
        if (Array.isArray(classData)) {
            if (classData.length > 1) {
                // Find batchId from the first element or strictly pass it?
                // `classData` entries have `batch_id` in them if we kept it? 
                // Wait, `renderRawCell` returns objects with `id`, `course` etc but NOT `batchId` explicitly in the mapped object.
                // I'll update `renderRawCell` to include batchId.
                setSelectionModalData({ classes: classData });
                return;
            }
            classData = classData[0];
        }

        if (!classData.id) {
            toast.error("Cannot edit this class (Missing ID). Try refreshing.");
            return;
        }
        setEditingId(classData.id);
        const routineEntry = routine.find(r => r.id === classData.id);

        if (routineEntry) {
            setFormData({
                day: routineEntry.day,
                time: routineEntry.time,
                batch_id: routineEntry.batch_id,
                course_id: routineEntry.course_id,
                faculty_id: routineEntry.faculty_id,
                room_id: routineEntry.room_id
            });
        }
        setShowModal(true);
    };

    const handleCellClick = (currentData) => {
        if (!currentData || currentData.length === 0) return;

        const facultyIds = currentData.map(d => String(d.facultyId));
        const selectFaculty = metadata.faculty.filter(f => facultyIds.includes(String(f.id)));
        
        setSelectedFacultyList(selectFaculty);
        setShowContactModal(true);
    };

    const handleSave = async () => {
        // Validation
        if (!formData.batch_id || !formData.course_id || !formData.faculty_id) {
            toast.error("Please fill all fields");
            return;
        }

        setLoading(true);
        const loadingToast = toast.loading(editingId ? 'Updating class...' : 'Adding class...');

        try {
            if (editingId) {
                await updateRoutineEntry(editingId, formData);
                toast.success('Class updated successfully!', { id: loadingToast });
            } else {
                await addRoutineEntry(formData);
                toast.success('Class added successfully!', { id: loadingToast });
            }
            await fetchData();
            setShowModal(false);
            resetForm();
        } catch (err) {
            console.error("Save Error:", err);
            const errorMessage = err.response?.data?.message || 'Failed to save class';
            toast.error(errorMessage, { id: loadingToast });
            setLoading(false);
        }
    };

    const handleDelete = async () => {
        if (!editingId) return;

        if (!window.confirm("Are you sure you want to delete this class?")) {
            return;
        }

        setLoading(true);
        const loadingToast = toast.loading('Deleting class...');
        try {
            await deleteRoutineEntry(editingId);
            await fetchData();
            toast.success('Class deleted successfully!', { id: loadingToast });
            setShowModal(false);
            resetForm();
        } catch (err) {
            console.error("Delete Error:", err);
            toast.error('Failed to delete class.', { id: loadingToast });
            setLoading(false);
        }
    };

    const handleBatchRoomUpdate = async (batchId) => {
        const loadingToast = toast.loading('Updating Default Room...');
        try {
            // Find current batch to preserve other fields
            const batch = metadata.batches.find(b => b.id === batchId);
            if (!batch) throw new Error("Batch not found");

            await updateBatch(batchId, { ...batch, default_room_id: selectedBatchRoom || null });
            await fetchData();
            toast.success('Room updated!', { id: loadingToast });
            setEditingBatchId(null);
        } catch (err) {
            console.error("Update Error:", err);
            toast.error('Failed to update room.', { id: loadingToast });
        }
    };

    // Helper functions
    const getRoomName = (id) => metadata.rooms.find(r => String(r.id) === String(id))?.room_number || 'TBA';
    const getFacultyInitials = (id) => metadata.faculty.find(f => String(f.id) === String(id))?.initials || metadata.faculty.find(f => String(f.id) === String(id))?.name?.split(' ').map(n => n[0]).join('') || 'TBA';
    const getCourseCode = (id) => {
        // Handle composite IDs like "201-401"
        const cleanId = String(id).split('-')[0];
        return metadata.courses.find(c => String(c.id) === cleanId)?.code || 'TBA';
    };
    const getCourseCredit = (id) => {
        const cleanId = String(id).split('-')[0];
        return metadata.courses.find(c => String(c.id) === cleanId)?.credit || 0;
    };

    const isLabCourse = (courseId) => {
        if (!courseId) return false;
        const cleanId = String(courseId).split('-')[0];
        const course = metadata.courses.find(c => String(c.id) === cleanId);
        if (!course) return false;

        // Priority 1: Check type explicitly
        if (course.type === 'Lab' || course.type === 'Sessional') return true;

        // Priority 2: Check for "Laboratory" or "Sessional" in name
        if (course.name.toLowerCase().includes('laboratory') || course.name.toLowerCase().includes('sessional')) return true;

        // Priority 3: Check Even ID rule (User Request)
        const codeParts = course.code.split('-');
        const lastPart = codeParts[codeParts.length - 1]; // e.g. "1102"
        const num = parseInt(lastPart);
        if (!isNaN(num) && num % 2 === 0) return true;

        return false;
    };

    // Helper to get configuration for a specific day
    const getConfigForDay = (day) => {
        if (!scheduleSettings.daily_overrides) return scheduleSettings.general || { theory_slots: [], lab_slots: [], slot_mapping: {} };
        return scheduleSettings.daily_overrides[day] || scheduleSettings.general;
    };

    // Current configuration based on selected day
    const currentDayConfig = getConfigForDay(selectedDay);
    const theorySlots = currentDayConfig.theory_slots;
    const labSlots = currentDayConfig.lab_slots;
    const slotMapping = currentDayConfig.slot_mapping;

    // const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

    // Dynamic slots based on view: Use full institutional slots for weekly view
    const currentTheorySlots = (viewMode === 'section' || viewMode === 'faculty')
        ? (scheduleSettings.general?.theory_slots || [])
        : (overtimeVisibility[selectedDay] ? theorySlots : theorySlots.slice(0, 6));

    const renderRawCell = (batchId, timeSlot, currentDay) => {
        // Find class for specific day
        const specificDayRoutine = routine.filter(r => r.day === currentDay);
        const labSlot = slotMapping[timeSlot];

        const classInfos = specificDayRoutine.filter(r =>
            r.batch_id === batchId &&
            (
                r.time === timeSlot ||
                (labSlot && r.time === labSlot) ||
                r.time.replace(' ', '') === timeSlot.replace(' ', '')
            )
        );

        if (!classInfos || classInfos.length === 0) return [];

        return classInfos.map(classInfo => {
            const isLab = isLabCourse(classInfo.course_id);
            const credit = getCourseCredit(classInfo.course_id);

            return {
                id: classInfo.id,
                course: getCourseCode(classInfo.course_id),
                faculty: getFacultyInitials(classInfo.faculty_id),
                room: getRoomName(classInfo.room_id),
                courseId: classInfo.course_id,
                facultyId: classInfo.faculty_id, // Added for context
                roomId: classInfo.room_id,       // Added for context
                isLab: isLab,
                credit: credit,
                originalTime: classInfo.time,
                batchId: batchId // Ensure batchId is available
            };
        });
    };

    // Modified to use renderRawCell for consistency
    const getCellData = (batchId, timeSlot) => renderRawCell(batchId, timeSlot, selectedDay);

    const renderRowCells = (batchId) => {
        const cells = [];
        let i = 0;
        while (i < currentTheorySlots.length) {
            const currentSlot = currentTheorySlots[i];
            const currentData = getCellData(batchId, currentSlot);

            let colSpan = 1;

            if (currentData && currentData.length > 0) {
                // Use first entry for colspan
                const firstEntry = currentData[0];
                if (firstEntry.isLab && labSlots.includes(firstEntry.originalTime)) {
                    colSpan = 2;
                }
            }

            // Safety check for colSpan extending beyond visible columns
            if (i + colSpan > currentTheorySlots.length) {
                colSpan = currentTheorySlots.length - i;
            }

            // Prepare display data directly
            const displayCourses = currentData.map(d => d.course).join(' / ');
            const displayFaculty = currentData.map(d => d.faculty).join(' / ');
            const displayRoom = currentData.map(d => d.room).join(' / ');
            const isLab = currentData.some(d => d.isLab);
            const isAlt = currentData.some(d => d.credit === 0.75 || d.credit === "0.75");
            const canAddSecond = currentData.length === 1 && isAlt;

            cells.push(
                <td key={currentSlot} colSpan={colSpan} className="px-2 py-2 border-r border-border text-center align-middle h-24 relative group">
                    {currentData.length > 0 ? (
                        <div
                            className={cn(
                                "flex flex-col items-center justify-center space-y-1 p-2 rounded-md transition-colors h-full w-full relative group",
                                "cursor-pointer hover:bg-muted/50"
                            )}
                            onClick={() => handleCellClick(currentData)}
                        >
                            <span className="font-bold text-foreground text-sm">{displayCourses}</span>
                            <span className="text-xs text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                                {displayFaculty}
                            </span>
                            {displayRoom && displayRoom !== 'TBA' && (
                                <span className="text-xs font-mono text-indigo-500 font-medium">
                                    R-{displayRoom}
                                </span>
                            )}
                            <div className="flex gap-1 justify-center mt-1">
                                {isLab && (
                                    <span className="text-[10px] text-emerald-600 font-bold uppercase tracking-wider">LAB</span>
                                )}
                                {isAlt && (
                                    <span className="text-[10px] text-orange-600 font-bold uppercase tracking-wider">ALT</span>
                                )}
                            </div>

                            {/* Hover Hint & Add Second Button */}
                            {canEdit && (
                                <span className="absolute top-1 right-1 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1">
                                    {canAddSecond && (
                                        <Button
                                            variant="ghost"
                                            size="icon"
                                            className="h-5 w-5 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-100 rounded-full"
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                openAddModal({ batch_id: batchId, time: currentSlot });
                                            }}
                                            title="Add Alternate Lab"
                                        >
                                            <Plus className="h-4 w-4" />
                                        </Button>
                                    )}
                                    <Edit2
                                        className="h-4 w-4 text-muted-foreground hover:text-indigo-600 cursor-pointer p-0.5"
                                        onClick={(e) => {
                                            e.stopPropagation();
                                            openEditModal(currentData);
                                        }}
                                    />
                                </span>
                            )}
                        </div>
                    ) : (
                        canEdit && (
                            <div
                                className="h-full w-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer hover:bg-muted/50 rounded-md"
                                onClick={() => openAddModal({ batch_id: batchId, time: currentSlot })}
                                title="Add Class"
                            >
                                <Plus className="h-5 w-5 text-muted-foreground/50 hover:text-indigo-500" />
                            </div>
                        )
                    )}
                </td>
            );

            i += colSpan;
        }
        return cells;
    };

    // Helper to get cell data for Section/Faculty views (Row = Day)
    const getWeeklyCellData = (day, timeSlot) => {
        let specificDayRoutine = routine.filter(r => r.day === day);
        const config = getConfigForDay(day);
        const labSlot = config.slot_mapping[timeSlot];

        let classInfos = [];

        if (viewMode === 'section') {
            if (!selectedBatchId) return [];
            classInfos = specificDayRoutine.filter(r =>
                r.batch_id === parseInt(selectedBatchId) &&
                (r.time === timeSlot || (labSlot && r.time === labSlot) || r.time.replace(' ', '') === timeSlot.replace(' ', ''))
            );
        } else if (viewMode === 'faculty') {
            if (!selectedFacultyId) return [];
            classInfos = specificDayRoutine.filter(r =>
                r.faculty_id === parseInt(selectedFacultyId) &&
                (r.time === timeSlot || (labSlot && r.time === labSlot) || r.time.replace(' ', '') === timeSlot.replace(' ', ''))
            );
        }

        if (!classInfos || classInfos.length === 0) return [];

        return classInfos.map(classInfo => {
            const isLab = isLabCourse(classInfo.course_id);
            const credit = getCourseCredit(classInfo.course_id);

            return {
                id: classInfo.id,
                course: getCourseCode(classInfo.course_id),
                faculty: getFacultyInitials(classInfo.faculty_id),
                room: getRoomName(classInfo.room_id),
                courseId: classInfo.course_id,
                facultyId: classInfo.faculty_id,
                roomId: classInfo.room_id,
                isLab: isLab,
                credit: credit,
                originalTime: classInfo.time,
                batchId: classInfo.batch_id
            };
        });
    };


    const renderWeeklyRows = (day) => {
        const cells = [];
        let i = 0;
        // If weekly view, we iterate the FULL header slots (currentTheorySlots which is 8 cols)
        // But we check if the slot is "open" for this specific day using overtimeVisibility[day]
        const slots = currentTheorySlots;

        while (i < slots.length) {
            const currentSlot = slots[i];

            // Check if this slot is active for the day
            const isOvertimeSlot = i >= 6; // Indices 6 and 7 are overtime
            // For Section/Faculty views, we always show overtime slots (User Request)
            const isDayActive = true;

            if (!isDayActive) {
                // Render placeholder/disabled cell
                cells.push(
                    <td key={currentSlot} className="px-2 py-2 border-r border-border text-center align-middle h-24 bg-muted/20">
                        <div className="h-full w-full flex items-center justify-center opacity-30 text-xs text-muted-foreground select-none">
                            -
                        </div>
                    </td>
                );
                i++;
                continue;
            }

            const config = getConfigForDay(day);
            const currentData = getWeeklyCellData(day, currentSlot);

            let colSpan = 1;
            if (currentData && currentData.length > 0) {
                const firstEntry = currentData[0];
                if (firstEntry.isLab && config.lab_slots.includes(firstEntry.originalTime)) {
                    colSpan = 2;
                }
            }

            if (i + colSpan > slots.length) {
                colSpan = slots.length - i;
            }

            // Prepare display data directly
            const displayCourses = currentData.map(d => d.course).join(' / ');
            const displayFaculty = currentData.map(d => d.faculty).join(' / ');
            const displayRoom = currentData.map(d => d.room).join(' / ');
            const isLab = currentData.some(d => d.isLab);
            const isAlt = currentData.some(d => d.credit === 0.75 || d.credit === "0.75");
            const canAddSecond = currentData.length === 1 && isAlt;

            cells.push(
                <td key={currentSlot} colSpan={colSpan} className="px-2 py-2 border-r border-border text-center align-middle h-24 relative group">
                    {currentData.length > 0 ? (
                        <div
                            className={cn(
                                "flex flex-col items-center justify-center space-y-1 p-2 rounded-md transition-colors h-full w-full relative group",
                                canEdit ? "cursor-pointer hover:bg-muted/50" : ""
                            )}
                            onClick={() => canEdit && openEditModal(currentData)}
                        >
                            <span className="font-bold text-foreground text-sm">{displayCourses}</span>
                            <span className="text-xs text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                                {viewMode === 'faculty' ? (
                                    metadata.batches.find(b => b.id === currentData[0].batchId)?.name + " " + (metadata.batches.find(b => b.id === currentData[0].batchId)?.section || '')
                                ) : (
                                    displayFaculty
                                )}
                            </span>
                            {displayRoom && displayRoom !== 'TBA' && (
                                <span className="text-xs font-mono text-indigo-500 font-medium">
                                    R-{displayRoom}
                                </span>
                            )}
                            <div className="flex gap-1 justify-center mt-1">
                                {isLab && (
                                    <span className="text-[10px] text-emerald-600 font-bold uppercase tracking-wider">LAB</span>
                                )}
                                {isAlt && (
                                    <span className="text-[10px] text-orange-600 font-bold uppercase tracking-wider">ALT</span>
                                )}
                            </div>

                            {/* Hover Hint & Add Second Button */}
                            {canEdit && (
                                <span className="absolute top-1 right-1 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1">
                                    {canAddSecond && (
                                        <Button
                                            variant="ghost"
                                            size="icon"
                                            className="h-5 w-5 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-100 rounded-full"
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                const overrides = { time: currentSlot, day: day };
                                                if (viewMode === 'section') overrides.batch_id = selectedBatchId;
                                                if (viewMode === 'faculty') overrides.faculty_id = selectedFacultyId;
                                                openAddModal(overrides);
                                            }}
                                            title="Add Alternate Lab"
                                        >
                                            <Plus className="h-4 w-4" />
                                        </Button>
                                    )}
                                    <Edit2 
                                        className="h-4 w-4 text-muted-foreground hover:text-indigo-600 cursor-pointer p-0.5" 
                                        onClick={(e) => {
                                            e.stopPropagation();
                                            openEditModal(currentData);
                                        }}
                                    />
                                </span>
                            )}
                        </div>
                    ) : (
                        canEdit && (
                            <div
                                className="h-full w-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer hover:bg-muted/50 rounded-md"
                                onClick={() => {
                                    const overrides = { time: currentSlot, day: day };
                                    if (viewMode === 'section') overrides.batch_id = selectedBatchId;
                                    if (viewMode === 'faculty') overrides.faculty_id = selectedFacultyId;
                                    openAddModal(overrides);
                                }}
                                title="Add Class"
                            >
                                <Plus className="h-5 w-5 text-muted-foreground/50 hover:text-indigo-500" />
                            </div>
                        )
                    )}
                </td>
            );

            i += colSpan;
        }
        return cells;
    };


    // Modified to use renderRawCell for consistency
    // const getCellData = (batchId, timeSlot) => renderRawCell(batchId, timeSlot, selectedDay);

    const downloadPDF = () => {
        let title = "Class Routine";
        let subtitle = "";
        let entityName = "";
        
        if (viewMode === 'master') {
            subtitle = `Master Routine - ${selectedDay}`;
            entityName = selectedDay;
        }
        if (viewMode === 'section') {
            const b = metadata.batches.find(b => String(b.id) === String(selectedBatchId));
            subtitle = `Section Routine - ${b ? b.name + ' (' + b.section + ')' : ''}`;
            entityName = b ? `${b.name} (${b.section})` : "Batch";
        }
        if (viewMode === 'faculty') {
            const f = metadata.faculty.find(f => String(f.id) === String(selectedFacultyId));
            subtitle = `Faculty Routine - ${f ? f.name : ''}`;
            entityName = f ? f.name : "Faculty";
        }

        const now = new Date();
        const timestamp = `${String(now.getDate()).padStart(2, '0')}-${String(now.getMonth() + 1).padStart(2, '0')}-${now.getFullYear()}_${String(now.getHours()).padStart(2, '0')}-${String(now.getMinutes()).padStart(2, '0')}`;
        const dynamicFileName = `${entityName}_${timestamp}`;

        const finalSettings = {
            ...pdfSettings,
            fileName: dynamicFileName,
            additionalText: dynamicFileName,
            // Clear unwanted sections for Routine View
            ccText: "",
            bottomSignatures: [],
            signatureImage: null,
            excludeSignatures: true
        };

        const tableColumn = [viewMode === 'master' ? "Batch" : "Day", ...currentTheorySlots];
        const tableRows = [];

        if (viewMode === 'master') {
            // Rows are Batches
            let visibleBatches = sortedBatches;

            visibleBatches.forEach(batch => {
                const row = [batch.name + (batch.section ? `\n(Sec ${batch.section})` : '')];
                let i = 0;
                while (i < currentTheorySlots.length) {
                    const slot = currentTheorySlots[i];
                    const data = getCellData(batch.id, slot);
                    if (data && data.length > 0) {
                        const isLab = data.some(d => d.isLab && labSlots.includes(d.originalTime));
                        
                        const cellContent = data.map(d => {
                            const courseText = d.isLab ? `${d.course} (LAB)` : d.course;
                            return `${courseText}\n${d.faculty}_${d.room !== 'TBA' ? d.room : 'TBA'}`;
                        }).join('\n-alt-\n');

                        let colSpan = 1;
                        if (isLab) {
                            // Find how many slots this lab actually spans in the visible header
                            const labEndTimeStr = data[0].originalTime.split('-')[1].trim();
                            // Find index of slot that matches the lab end time
                            const endSlotIndex = currentTheorySlots.findIndex(s => s.endsWith(labEndTimeStr));
                            if (endSlotIndex !== -1 && endSlotIndex >= i) {
                                colSpan = (endSlotIndex - i) + 1;
                            } else {
                                colSpan = 2; // Fallback
                            }
                        }
                        if (i + colSpan > currentTheorySlots.length) {
                            colSpan = currentTheorySlots.length - i;
                        }

                        if (colSpan > 1) {
                            row.push({ content: cellContent, colSpan: colSpan });
                            i += (colSpan - 1);
                        } else {
                            row.push(cellContent);
                        }
                    } else {
                        row.push('-');
                    }
                    i++;
                }
                tableRows.push(row);
            });
        } else {
            // Rows are Days
            days.forEach(day => {
                const row = [day];
                let i = 0;
                while (i < currentTheorySlots.length) {
                    const slot = currentTheorySlots[i];
                    const data = getWeeklyCellData(day, slot);
                    if (data && data.length > 0) {
                        const dayConfig = getConfigForDay(day);
                        const isLab = data.some(d => d.isLab && dayConfig.lab_slots.includes(d.originalTime));

                        const cellContent = data.map(d => {
                            const facultyOrBatch = viewMode === 'faculty' 
                                ? (metadata.batches.find(b => String(b.id) === String(d.batchId))?.name + (metadata.batches.find(b => String(b.id) === String(d.batchId))?.section ? ' ' + metadata.batches.find(b => String(b.id) === String(d.batchId))?.section : '')) 
                                : d.faculty;
                            const courseText = d.isLab ? `${d.course} (LAB)` : d.course;
                            return `${courseText}\n${facultyOrBatch}_${d.room !== 'TBA' ? d.room : 'TBA'}`;
                        }).join('\n-alt-\n');

                        let colSpan = isLab ? 2 : 1;
                        if (i + colSpan > currentTheorySlots.length) {
                            colSpan = currentTheorySlots.length - i;
                        }

                        if (colSpan > 1) {
                            row.push({ content: cellContent, colSpan: colSpan });
                            i += (colSpan - 1);
                        } else {
                            row.push(cellContent);
                        }
                    } else {
                        row.push('-');
                    }
                    i++;
                }
                tableRows.push(row);
            });
        }

        generateRoutineViewPDF(title, subtitle, tableColumn, tableRows, finalSettings);
    };

    // Determine active time slots based on selected course
    const activeTimeSlots = isLabCourse(formData.course_id) ? labSlots : theorySlots;

    const renderTableHeader = () => (
        <thead className="text-xs uppercase bg-muted/50 text-muted-foreground">
            <tr>
                <th className="px-4 py-4 w-48 font-bold border-r border-border text-center sticky left-0 bg-secondary z-20 transition-colors">
                    {(viewMode === 'master') ? 'Batch' : 'Day'}
                </th>
                {currentTheorySlots.map(slot => (
                    <th key={slot} className="px-4 py-3 border-r border-border text-center min-w-[120px]">
                        {slot}
                    </th>
                ))}
            </tr>
        </thead>
    );

    return (
        <div className="space-y-6 max-w-[100vw] overflow-x-hidden px-4 relative">
            {/* Header Section */}
            <div className="flex flex-col gap-4">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div>
                        <h2 className="text-3xl font-bold tracking-tight text-foreground">Class Schedule</h2>
                        <p className="text-muted-foreground mt-1">
                            {viewMode === 'master' && 'Master Routine View'}
                            {viewMode === 'section' && 'Section Weekly View'}
                            {viewMode === 'faculty' && 'Faculty Weekly View'}
                        </p>
                    </div>
                    <div className="flex space-x-3">
                        {canEdit && (
                            <>
                                <Button onClick={() => openAddModal()} className="shadow-lg shadow-emerald-500/20 bg-emerald-600 hover:bg-emerald-700">
                                    <Plus className="mr-2 h-4 w-4" />
                                    Add Class
                                </Button>
                                <Button variant="outline" onClick={() => setShowSettingsModal(true)}>
                                    <Settings className="mr-2 h-4 w-4" />
                                    Settings
                                </Button>
                            </>
                        )}
                        <div className="flex bg-muted/30 p-1 rounded-md border border-border">
                            {user && canEdit && (
                                <Button variant="ghost" size="sm" onClick={() => setIsPdfModalOpen(true)} title="PDF Settings" className="text-muted-foreground hover:text-indigo-600 border-r border-border rounded-r-none pr-3">
                                    <Settings className="h-4 w-4" />
                                </Button>
                            )}
                            <Button 
                                variant="default" 
                                className={cn(
                                    "bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm",
                                    user && canEdit ? "rounded-l-none" : ""
                                )} 
                                onClick={downloadPDF}
                            >
                                <Download className="mr-2 h-4 w-4" />
                                Download PDF
                            </Button>
                        </div>
                    </div>
                </div>

                {/* View Controls */}
                <div className="flex flex-wrap items-center gap-4 bg-muted/30 p-4 rounded-lg border border-border">
                    {/* View Mode Switcher */}
                    <div className="flex bg-background rounded-md border border-border p-1">
                        {['master', 'section', 'faculty'].map(mode => (
                            <button
                                key={mode}
                                onClick={() => setViewMode(mode)}
                                className={cn(
                                    "px-4 py-2 text-sm font-medium rounded-sm transition-all capitalize",
                                    viewMode === mode ? "bg-indigo-600 text-white shadow-sm" : "text-muted-foreground hover:text-foreground hover:bg-muted"
                                )}
                            >
                                {mode} View
                            </button>
                        ))}
                    </div>

                    <div className="h-8 w-px bg-border hidden md:block"></div>

                    {/* Conditional Selectors */}
                    {(viewMode === 'master') && (
                        <>
                            <div className="flex items-center gap-2">
                                <Calendar className="w-4 h-4 text-muted-foreground" />
                                <Select
                                    value={selectedDay}
                                    onChange={(e) => setSelectedDay(e.target.value)}
                                    className="w-40"
                                >
                                    {days.map(day => <option key={day} value={day}>{day}</option>)}
                                </Select>
                            </div>

                            {canEdit && (
                                <div className="flex items-center gap-2 px-2 border-l border-border ml-2">
                                    <span className="text-xs text-muted-foreground font-medium whitespace-nowrap hidden sm:inline">Evening:</span>
                                    <button
                                        onClick={() => setOvertimeVisibility(prev => ({
                                            ...prev,
                                            [selectedDay]: !prev[selectedDay]
                                        }))}
                                        className={cn(
                                            "relative inline-flex h-5 w-9 items-center rounded-full transition-colors focus:outline-none focus:ring-1 focus:ring-indigo-500",
                                            overtimeVisibility[selectedDay] ? "bg-indigo-600" : "bg-muted-foreground/30"
                                        )}
                                        title={`Toggle evening slots for ${selectedDay}`}
                                    >
                                        <span
                                            className={cn(
                                                "inline-block h-3.5 w-3.5 transform rounded-full bg-white transition-transform",
                                                overtimeVisibility[selectedDay] ? "translate-x-4" : "translate-x-0.5"
                                            )}
                                        />
                                    </button>
                                </div>
                            )}
                        </>
                    )}

                    {viewMode === 'section' && (
                        <div className="flex items-center gap-2">
                            <span className="text-sm font-medium">Section:</span>
                            <Select
                                value={selectedBatchId}
                                onChange={(e) => setSelectedBatchId(e.target.value)}
                                className="w-60"
                            >
                                <option value="">Select Section</option>
                                {sortedBatches.map(b => (
                                    <option key={b.id} value={b.id}>{b.name} - {b.section}</option>
                                ))}
                            </Select>
                        </div>
                    )}



                    {viewMode === 'faculty' && (
                        <div className="flex items-center gap-2">
                            <span className="text-sm font-medium">Faculty:</span>
                            <Select
                                value={selectedFacultyId}
                                onChange={(e) => setSelectedFacultyId(e.target.value)}
                                className="w-60"
                            >
                                <option value="">Select Faculty</option>
                                {metadata.faculty.map(f => (
                                    <option key={f.id} value={f.id}>{f.name} ({f.initials})</option>
                                ))}
                            </Select>
                        </div>
                    )}
                </div>
            </div>

            {/* Class Modal (add/edit) */}
            {showModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-card w-full max-w-lg rounded-xl shadow-2xl border border-border animate-in fade-in zoom-in-95 duration-200">
                        <div className="flex items-center justify-between p-4 border-b border-border">
                            <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
                                {editingId ? (
                                    <>
                                        <Edit2 className="h-4 w-4 text-indigo-500" />
                                        Edit Class Details
                                    </>
                                ) : (
                                    <>
                                        <Plus className="h-4 w-4 text-emerald-500" />
                                        Add Manual Class
                                    </>
                                )}
                            </h3>
                            <button onClick={() => setShowModal(false)} className="text-muted-foreground hover:text-foreground">
                                <X className="h-5 w-5" />
                            </button>
                        </div>
                        <div className="p-6 space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">Day</label>
                                    <Select
                                        value={formData.day}
                                        onChange={(e) => setFormData({ ...formData, day: e.target.value })}
                                        className="w-full"
                                    >
                                        {days.map(d => <option key={d} value={d}>{d}</option>)}
                                    </Select>
                                </div>
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">
                                        Time Slot
                                        {isLabCourse(formData.course_id) && <span className="text-xs text-emerald-600 ml-2">(Lab Duration)</span>}
                                    </label>
                                    <Select
                                        value={formData.time}
                                        onChange={(e) => setFormData({ ...formData, time: e.target.value })}
                                        className="w-full"
                                    >
                                        <option value="">Select Time</option>
                                        {activeTimeSlots.map(t => <option key={t} value={t}>{t}</option>)}
                                    </Select>
                                </div>
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-medium">Batch</label>
                                <Select
                                    value={formData.batch_id}
                                    onChange={(e) => setFormData({ ...formData, batch_id: e.target.value })}
                                    className="w-full"
                                >
                                    <option value="">Select Batch</option>
                                    {sortedBatches.map(b => (
                                        <option key={b.id} value={b.id}>{b.name} (Sec-{b.section})</option>
                                    ))}
                                </Select>
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-medium">Course</label>
                                <Select
                                    value={formData.course_id}
                                    onChange={(e) => {
                                        const newCourseId = e.target.value;
                                        let newTime = formData.time;

                                        // Intelligent Time Slot Mapping
                                        if (newCourseId && formData.time) {
                                            const isLab = isLabCourse(newCourseId);
                                            // Case 1: Switching to Lab Course
                                            if (isLab) {
                                                // Try to find a lab slot that starts at the same time
                                                // e.g. 08:00-09:15 -> 08:00-10:30
                                                const theoryStart = formData.time.split('-')[0].trim();
                                                const matchingLabSlot = labSlots.find(ls => ls.startsWith(theoryStart));

                                                if (matchingLabSlot) {
                                                    newTime = matchingLabSlot;
                                                } else if (!labSlots.includes(formData.time)) {
                                                    // If current time isn't a valid lab slot and no match found, reset
                                                    newTime = '';
                                                }
                                            }
                                            // Case 2: Switching to Theory Course
                                            else {
                                                // If currently selected time is a Lab slot (longer), try to revert to standard slot
                                                if (labSlots.includes(formData.time)) {
                                                    const labStart = formData.time.split('-')[0].trim();
                                                    const matchingTheorySlot = theorySlots.find(ts => ts.startsWith(labStart));
                                                    if (matchingTheorySlot) {
                                                        newTime = matchingTheorySlot;
                                                    } else {
                                                        newTime = '';
                                                    }
                                                }
                                                // If it was already a theory slot, keep it.
                                            }
                                        }

                                        setFormData({ ...formData, course_id: newCourseId, time: newTime });
                                    }}
                                    className="w-full"
                                >
                                    <option value="">Select Course</option>
                                    {(() => {
                                        const selectedBatch = metadata.batches.find(b => String(b.id) === String(formData.batch_id));
                                        let filteredCourses = metadata.courses;

                                        if (selectedBatch) {
                                            const parts = selectedBatch.name.split(" ");
                                            const yearNum = parseInt(parts[0]) || 0;
                                            const semNum = parts.length >= 3 ? parseInt(parts[2]) : 0;
                                            
                                            if (yearNum && semNum) {
                                                const prefix = `${yearNum}${semNum}`;
                                                const filtered = metadata.courses.filter(c => {
                                                    const numericPart = c.code.match(/\\d+/);
                                                    return numericPart && numericPart[0].startsWith(prefix);
                                                });
                                                if (filtered.length > 0) filteredCourses = filtered;
                                            }
                                        }

                                        return [...filteredCourses]
                                            .sort((a, b) => {
                                                const aNum = parseInt(a.code.match(/\\d+/)?.[0] || 0);
                                                const bNum = parseInt(b.code.match(/\\d+/)?.[0] || 0);
                                                return aNum - bNum || a.code.localeCompare(b.code);
                                            })
                                            .map(c => (
                                                <option key={c.id} value={c.id}>
                                                    {c.code} - {c.name} {c.type === "Lab" ? "(Lab)" : ""}
                                                </option>
                                            ));
                                    })()}
                                </Select>
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">Faculty</label>
                                    <SearchableSelect
                                        options={metadata.faculty
                                            .sort((a, b) => a.name.localeCompare(b.name))
                                            .map(f => ({
                                                value: f.id,
                                                label: `${f.name} (${f.initials})`,
                                                searchTerms: `${f.name} ${f.initials}`
                                            }))
                                        }
                                        value={formData.faculty_id}
                                        onValueChange={(val) => setFormData({ ...formData, faculty_id: val })}
                                        placeholder="Select Faculty"
                                        searchPlaceholder="Search name or initials..."
                                    />
                                </div>
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">Room</label>
                                    <SearchableSelect
                                        options={metadata.rooms.filter(r => {
                                            if (!formData.course_id) return true;
                                            const courseId = String(formData.course_id).split("-")[0];
                                            const course = metadata.courses.find(c => String(c.id) === courseId);
                                            if (!course) return true;
                                            if (course.code === "HUM-1142" || course.code === "Hum-1142") return true;
                                            const isLab = isLabCourse(formData.course_id);
                                            return isLab ? r.type === "Lab" : r.type === "Theory";
                                        })
                                        .sort((a, b) => {
                                            const aNum = parseInt(a.room_number.match(/\d+/)?.[0] || 0);
                                            const bNum = parseInt(b.room_number.match(/\d+/)?.[0] || 0);
                                            return aNum - bNum || a.room_number.localeCompare(b.room_number);
                                        })
                                        .map(r => ({
                                            value: r.id,
                                            label: `Room ${r.room_number} (${r.type === "Theory" ? "Class" : "Laboratory"})`,
                                            searchTerms: r.room_number
                                        }))}
                                        value={formData.room_id}
                                        onValueChange={(val) => setFormData({ ...formData, room_id: val })}
                                        placeholder="Select Room"
                                        searchPlaceholder="Search room number..."
                                    />
                                </div>
                            </div>

                            <div className="pt-2 flex gap-3">
                                {editingId && (
                                    <Button
                                        variant="destructive"
                                        onClick={handleDelete}
                                        className="flex-1"
                                    >
                                        <Trash2 className="mr-2 h-4 w-4" />
                                        Delete
                                    </Button>
                                )}
                                <Button
                                    onClick={handleSave}
                                    className={cn(
                                        "flex-[2]",
                                        editingId ? "bg-indigo-600 hover:bg-indigo-700" : "bg-emerald-600 hover:bg-emerald-700"
                                    )}
                                >
                                    {editingId ? (
                                        <>
                                            <Check className="mr-2 h-4 w-4" />
                                            Save Changes
                                        </>
                                    ) : (
                                        <>
                                            <Plus className="mr-2 h-4 w-4" />
                                            Add Class to Routine
                                        </>
                                    )}
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Day Selector Tabs and Overtime Toggle */}
            {/* This section is now integrated into the main view controls */}
            {/* <div className="flex flex-col sm:flex-row items-end sm:items-center justify-between gap-2 border-b border-border pb-1">
                <div className="flex overflow-x-auto space-x-1 w-full sm:w-auto">
                    {days.map(day => (
                        <button
                            key={day}
                            onClick={() => setSelectedDay(day)}
                            className={cn(
                                "px-6 py-2.5 text-sm font-medium rounded-t-lg transition-colors whitespace-nowrap flex-1 sm:flex-none",
                                selectedDay === day
                                    ? "bg-card text-indigo-600 border-t-2 border-indigo-600 shadow-sm dark:bg-muted dark:text-indigo-400"
                                    : "text-muted-foreground hover:text-foreground hover:bg-muted/50"
                            )}
                        >
                            {day}
                        </button>
                    ))}
                </div>

                {canEdit && (
                    <div className="flex items-center gap-2 px-2 pb-1 sm:pb-0">
                        <span className="text-xs text-muted-foreground font-medium whitespace-nowrap">Overtime (Evening):</span>
                        <button
                            onClick={() => setOvertimeVisibility(prev => ({
                                ...prev,
                                [selectedDay]: !prev[selectedDay]
                            }))}
                            className={cn(
                                "relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2",
                                overtimeVisibility[selectedDay] ? "bg-indigo-600" : "bg-muted"
                            )}
                            title={`Toggle evening slots for ${selectedDay}`}
                        >
                            <span
                                className={cn(
                                    "inline-block h-4 w-4 transform rounded-full bg-white transition-transform",
                                    overtimeVisibility[selectedDay] ? "translate-x-6" : "translate-x-1"
                                )}
                            />
                        </button>
                    </div>
                )}
            </div>

        <div className="space-y-6 max-w-[100vw] overflow-x-hidden px-4 relative">
            {/* Header Section */}
            {/* ... rest of your code ... */}
            {/* Sticky Duplicate Header */}
            {showStickyHeader && (
                <div 
                    className="fixed top-[64px] z-40 bg-card border-b border-border shadow-md pointer-events-auto table-container-wrapper"
                    style={{ left: headerLayout.left, width: headerLayout.width }}
                >
                    <div 
                        className="overflow-x-auto table-scroll-area" 
                        ref={duplicateHeaderRef}
                        style={{ width: '100%' }}
                    >
                        <table className="w-full text-sm text-left border-collapse" style={{ width: tableWidth }}>
                            {renderTableHeader()}
                        </table>
                    </div>
                </div>
            )}

            {/* Master Schedule Table */}
            <div className="bg-card rounded-lg border border-border shadow-sm overflow-hidden table-container-wrapper">
                {/* Top Scrollbar */}
                <div
                    ref={topScrollContainerRef}
                    className="overflow-x-auto border-b border-border bg-muted/10 table-scroll-area"
                    style={{ height: '16px' }}
                >
                    <div style={{ width: tableWidth, height: '1px' }}></div>
                </div>

                <div className="overflow-x-auto table-scroll-area" ref={tableContainerRef}>
                    <table id="routine-view-table" className="w-full text-sm text-left border-collapse">
                        {renderTableHeader()}
                        <tbody className="divide-y divide-border">
                            {/* Logic for Master View: Rows = Batches */}
                            {(viewMode === 'master') && (
                                <>
                                    {sortedBatches.map(batch => (
                                            <tr key={batch.id} className="hover:bg-muted/30 transition-colors">
                                                <td className="px-4 py-3 font-semibold text-foreground border-r border-border sticky left-0 bg-card z-10 whitespace-nowrap min-w-[200px]">
                                                    <div className="text-xs text-muted-foreground">{batch.name}</div>
                                                    <div className="font-bold text-indigo-600 dark:text-indigo-400">Section {batch.section}</div>
                                                    <div
                                                        className={cn(
                                                            "mt-1 flex items-center gap-1 text-[10px] text-muted-foreground px-2 py-1 rounded w-fit transition-colors",
                                                            canEdit ? "bg-muted/50 cursor-pointer hover:bg-indigo-100 hover:text-indigo-700" : ""
                                                        )}
                                                        onClick={() => {
                                                            if (!canEdit) return;
                                                            setEditingBatchId(batch.id);
                                                            setSelectedBatchRoom(batch.default_room_id || '');
                                                        }}
                                                        title="Edit Default Room"
                                                    >
                                                        <MapPin className="w-3 h-3" />
                                                        {editingBatchId === batch.id ? (
                                                            <div className="flex items-center gap-2" onClick={e => e.stopPropagation()}>
                                                                <select
                                                                    className="h-6 text-[10px] bg-background border rounded"
                                                                    value={selectedBatchRoom}
                                                                    onChange={(e) => setSelectedBatchRoom(e.target.value)}
                                                                >
                                                                    <option value="">Select</option>
                                                                    {metadata.rooms.map(r => (
                                                                        <option key={r.id} value={r.id}>{r.room_number}</option>
                                                                    ))}
                                                                </select>
                                                                <Check
                                                                    className="w-4 h-4 text-emerald-600 cursor-pointer hover:scale-110"
                                                                    onClick={() => handleBatchRoomUpdate(batch.id)}
                                                                />
                                                                <X
                                                                    className="w-4 h-4 text-red-500 cursor-pointer hover:scale-110"
                                                                    onClick={() => setEditingBatchId(null)}
                                                                />
                                                            </div>
                                                        ) : (
                                                            getRoomName(batch.default_room_id) !== 'TBA' ? (
                                                                <span>Room: {getRoomName(batch.default_room_id)}</span>
                                                            ) : null
                                                        )}
                                                    </div>
                                                </td>
                                                {renderRowCells(batch.id)}
                                            </tr>
                                        ))}
                                    {sortedBatches.length === 0 && (
                                        <tr>
                                            <td colSpan={currentTheorySlots.length + 1} className="px-4 py-8 text-center text-muted-foreground">
                                                No batches found.
                                            </td>
                                        </tr>
                                    )}
                                </>
                            )}

                            {/* Logic for Section/Faculty View: Rows = Days */}
                            {(viewMode === 'section' || viewMode === 'faculty') && (
                                <>
                                    {days.map(day => (
                                        <tr key={day} className="hover:bg-muted/30 transition-colors">
                                            <td className="px-4 py-4 font-semibold text-foreground border-r border-border sticky left-0 bg-card z-10 text-center min-w-[150px]">
                                                {day}
                                            </td>
                                            {renderWeeklyRows(day)}
                                        </tr>
                                    ))}
                                    {((viewMode === 'section' && !selectedBatchId) || (viewMode === 'faculty' && !selectedFacultyId)) && (
                                        <tr>
                                            <td colSpan={currentTheorySlots.length + 1} className="px-4 py-8 text-center text-muted-foreground">
                                                Please select a {viewMode} to view schedule
                                            </td>
                                        </tr>
                                    )}
                                </>
                            )}
                        </tbody>
                    </table>
                </div>
                <FacultyContactModal
                isOpen={showContactModal}
                onClose={() => setShowContactModal(false)}
                facultyList={selectedFacultyList}
            />

            {/* Selection Modal for Multi-Class Slots */}
            {selectionModalData && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
                        <div className="bg-card w-full max-w-sm rounded-lg shadow-lg border border-border p-6 space-y-4">
                            <div className="flex justify-between items-center mb-2">
                                <h3 className="text-lg font-semibold">Select Class to Edit</h3>
                                <Button variant="ghost" size="icon" onClick={() => setSelectionModalData(null)}>
                                    <X className="h-4 w-4" />
                                </Button>
                            </div>
                            <div className="space-y-2">
                                {selectionModalData.classes.map((cls) => (
                                    <div
                                        key={cls.id}
                                        className={cn(
                                            "flex items-center justify-between p-3 rounded-md border border-border bg-muted/20 transition-colors",
                                            canEdit ? "hover:bg-muted/40 cursor-pointer" : ""
                                        )}
                                        onClick={() => {
                                            if (!canEdit) return;
                                            setSelectionModalData(null);
                                            openEditModal(cls);
                                        }}
                                    >
                                        <div>
                                            <div className="font-bold text-sm">{cls.course}</div>
                                            <div className="text-xs text-muted-foreground">
                                                {cls.faculty} {cls.room && cls.room !== 'TBA' ? `| R-${cls.room}` : ''}
                                            </div>
                                        </div>
                                        {canEdit && (
                                            <div className="p-1.5 rounded-full bg-primary/10 text-primary">
                                                <Edit2 className="h-3.5 w-3.5" />
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* Settings Modal */}
            <SettingsModal
                isOpen={showSettingsModal}
                onClose={() => setShowSettingsModal(false)}
                onSettingsUpdated={(newSettings) => setScheduleSettings(newSettings)}
            />

            {/* PDF Settings Modal */}
            <PdfDownloadModal
                isOpen={isPdfModalOpen}
                onClose={() => setIsPdfModalOpen(false)}
                initialSettings={pdfSettings}
                onSave={handleSavePdfSettings}
                isRoutineView={true}
            />

        </div>
    );
};

export default RoutineView;
