import React, { useState, useEffect, useRef } from 'react';
import { getRoutine, getRooms, getFaculty, getBatches, getCourses, updateBatch, addRoutineEntry, updateRoutineEntry, deleteRoutineEntry, clearRoutine, getSettings, updateSettings, exportRoutine, importRoutine, getStudents } from '../services/api';
import { generateWeeklyRoutinePDF } from '../utils/pdfGenerator';
import { Download, Check, X, MapPin, Plus, Edit2, Trash, Trash2, Upload, HardDriveDownload, Cloud, Search } from 'lucide-react';
import { Button } from './ui/Button';
import { SearchableSelect } from './ui/SearchableSelect';
import toast from 'react-hot-toast';
import { cn } from '../lib/utils';
import { useNavigate } from 'react-router-dom';
import SettingsModal from './SettingsModal';
import PdfDownloadModal from './PdfDownloadModal';
import { Settings, Settings2 } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import UnifiedContactModal from './ui/UnifiedContactModal';
import SelectionModal from './ui/SelectionModal';
import CloudRoutineBackupModal from './CloudRoutineBackupModal';

const WeekRoutineView = ({ overtimeVisibility, setOvertimeVisibility }) => {
    const { user, hasPermission } = useAuth();
    const canEdit = hasPermission('edit_week_routine');
    const [routine, setRoutine] = useState([]);
    const [metadata, setMetadata] = useState({ rooms: [], faculty: [], batches: [], courses: [], students: [] });
    const [loading, setLoading] = useState(true);
    // Removed local overtimeVisibility state, now using props

    // Batch Room Editing State
    const [editingBatchId, setEditingBatchId] = useState(null);
    const [selectedBatchRoom, setSelectedBatchRoom] = useState('');

    // Scroll Sync Refs & State
    const tableContainerRef = useRef(null);
    const topScrollContainerRef = useRef(null);
    const duplicateHeaderRef = useRef(null);
    const [tableWidth, setTableWidth] = useState(0);
    const [showStickyHeader, setShowStickyHeader] = useState(false);
    const [headerLayout, setHeaderLayout] = useState({ left: 0, width: 0 });

    // Add Class Modal State
    const [isAddModalOpen, setIsAddModalOpen] = useState(false);
    const [editingRoutineId, setEditingRoutineId] = useState(null);
    const [newClassData, setNewClassData] = useState({
        day: '',
        time: '',
        batchId: '',
        courseId: '',
        facultyId: '',
        roomId: '',
        additional_text: ''
    });

    // Multi-Class Selection Modal State
    const [selectionModalData, setSelectionModalData] = useState(null); // { classes: [], batchId: '' }

    // Settings State
    const [showSettingsModal, setShowSettingsModal] = useState(false);
    const [isPdfModalOpen, setIsPdfModalOpen] = useState(false);
    const [isCloudModalOpen, setIsCloudModalOpen] = useState(false);
    const [scheduleSettings, setScheduleSettings] = useState({
        general: { theory_slots: [], lab_slots: [], slot_mapping: {} },
        daily_overrides: {}
    });

    // Unified contact modal state
    const [showContactModal, setShowContactModal] = useState(false);
    const [selectedFacultyList, setSelectedFacultyList] = useState([]);
    const [selectedCRList, setSelectedCRList] = useState([]);
    const [contactSmartDefaults, setContactSmartDefaults] = useState(false);
    const [activeBatchInfo, setActiveBatchInfo] = useState({ id: '', name: '', section: '' });

    const defaultPdfSettings = {
        universityName: "North Western University",
        semesterName: "Spring 2026",
        additionalText: "Dept. of Computer Science & Engineering",
        footerLeftText: "Generated by NWU Smart Routine System",
        footerRightText: "",
        fontStyle: "helvetica",
        fontSize: 7,
        headerFontSize: 16
    };

    // Load initial PDF settings in fetchData
    const [pdfSettings, setPdfSettings] = useState(defaultPdfSettings);

    const navigate = useNavigate();
    const fileInputRef = useRef(null);

    useEffect(() => {
        fetchData();
    }, []);

    const fetchData = async () => {
        try {
            const results = await Promise.all([
                getRoutine(),
                getRooms(),
                getFaculty(),
                getBatches(),
                getCourses(),
                getSettings('app_settings'),
                getSettings('pdf_settings_week'),
                getStudents()
            ]);

            const routineRes = results[0];
            const roomsRes = results[1];
            const facultyRes = results[2];
            const batchesRes = results[3];
            const coursesRes = results[4];
            const settingsRes = results[5];
            const pdfSettingsRes = results[6];
            const studentsRes = results[7];

            setRoutine(routineRes.data);
            setMetadata({
                rooms: roomsRes.data,
                faculty: facultyRes.data,
                batches: batchesRes.data,
                courses: coursesRes.data,
                students: studentsRes?.data || []
            });
            if (settingsRes.data.success) {
                const settingsData = settingsRes.data.data;
                setScheduleSettings(settingsData);
                // Update form default if theory slots available in general config
                if (settingsData.general?.theory_slots?.length > 0) {
                    setNewClassData(prev => ({ ...prev, time: settingsData.general.theory_slots[0] }));
                }
            }
            if (pdfSettingsRes.data.success && Object.keys(pdfSettingsRes.data.data).length > 0) {
                setPdfSettings(pdfSettingsRes.data.data);
            }
            setLoading(false);
        } catch (err) {
            console.error(err);
            setLoading(false);
        }
    };
    const sortedBatches = React.useMemo(() => {
        if (!metadata.batches) return [];
        return [...metadata.batches].sort((a, b) => {
            const getSortMetadata = (name) => {
                const safeName = name || '';
                const parts = safeName.split(' ');
                const yearNum = parseInt(parts[0]) || 0;
                const semNum = parts.length >= 3 ? parseInt(parts[2]) : 0;
                return { year: yearNum, sem: semNum };
            };
            const metaA = getSortMetadata(a.name);
            const metaB = getSortMetadata(b.name);
            if (metaA.year !== metaB.year) return metaA.year - metaB.year;
            if (metaA.sem !== metaB.sem) return metaA.sem - metaB.sem;
            return (a.section || '').localeCompare(b.section || '');
        });
    }, [metadata.batches]);
    
    const sortedRooms = React.useMemo(() => {
        if (!metadata.rooms) return [];
        return [...metadata.rooms].sort((a, b) => {
            const numA = parseInt(a.room_number.match(/\d+/)?.[0] || 0);
            const numB = parseInt(b.room_number.match(/\d+/)?.[0] || 0);
            return numA - numB || a.room_number.localeCompare(b.room_number);
        });
    }, [metadata.rooms]);

    // Sync scroll position
    useEffect(() => {
        const table = tableContainerRef.current;
        const top = topScrollContainerRef.current;

        if (!table || !top) return;

        const handleTableScroll = () => {
            if (topScrollContainerRef.current && tableContainerRef.current) {
                const scrollLeft = tableContainerRef.current.scrollLeft;
                if (Math.abs(topScrollContainerRef.current.scrollLeft - scrollLeft) > 1) {
                    topScrollContainerRef.current.scrollLeft = scrollLeft;
                }
                if (duplicateHeaderRef.current && Math.abs(duplicateHeaderRef.current.scrollLeft - scrollLeft) > 1) {
                    duplicateHeaderRef.current.scrollLeft = scrollLeft;
                }
            }
        };

        const handleTopScroll = () => {
            if (tableContainerRef.current && topScrollContainerRef.current) {
                const scrollLeft = topScrollContainerRef.current.scrollLeft;
                if (Math.abs(tableContainerRef.current.scrollLeft - scrollLeft) > 1) {
                    tableContainerRef.current.scrollLeft = scrollLeft;
                }
                if (duplicateHeaderRef.current && Math.abs(duplicateHeaderRef.current.scrollLeft - scrollLeft) > 1) {
                    duplicateHeaderRef.current.scrollLeft = scrollLeft;
                }
            }
        };

        table.addEventListener('scroll', handleTableScroll);
        top.addEventListener('scroll', handleTopScroll);

        return () => {
            table.removeEventListener('scroll', handleTableScroll);
            top.removeEventListener('scroll', handleTopScroll);
        };
    }, []);

    // Effect for duplicate header scrolling and syncing widths
    useEffect(() => {
        const dup = duplicateHeaderRef.current;
        const table = tableContainerRef.current;
        const top = topScrollContainerRef.current;

        const handleDupScroll = () => {
            if (!dup) return;
            const scrollLeft = dup.scrollLeft;
            if (table && Math.abs(table.scrollLeft - scrollLeft) > 1) table.scrollLeft = scrollLeft;
            if (top && Math.abs(top.scrollLeft - scrollLeft) > 1) top.scrollLeft = scrollLeft;
        };

        if (dup) {
            dup.addEventListener('scroll', handleDupScroll);
            if (table) dup.scrollLeft = table.scrollLeft;
        }

        // Sync widths of columns
        if (showStickyHeader && dup && table) {
            const originalThs = table.querySelectorAll('thead th');
            const duplicateThs = dup.querySelectorAll('thead th');
            if (originalThs.length === duplicateThs.length) {
                for (let i = 0; i < originalThs.length; i++) {
                    duplicateThs[i].style.minWidth = `${originalThs[i].offsetWidth}px`;
                    duplicateThs[i].style.width = `${originalThs[i].offsetWidth}px`;
                }
            }
        }

        return () => {
            if (dup) dup.removeEventListener('scroll', handleDupScroll);
        };
    }, [showStickyHeader, tableWidth, routine, overtimeVisibility]);

    // Track window scroll for sticky header visibility
    useEffect(() => {
        const handleWindowScroll = () => {
            if (tableContainerRef.current) {
                const rect = tableContainerRef.current.getBoundingClientRect();
                // 64px is navbar height. Support intersection below.
                if (rect.top <= 64 && rect.bottom > 150) {
                    setShowStickyHeader(true);
                    setHeaderLayout({ left: rect.left, width: rect.width });
                } else {
                    setShowStickyHeader(false);
                }
            }
        };

        window.addEventListener('scroll', handleWindowScroll);
        window.addEventListener('resize', handleWindowScroll);
        handleWindowScroll(); // Initialize checking

        return () => {
            window.removeEventListener('scroll', handleWindowScroll);
            window.removeEventListener('resize', handleWindowScroll);
        };
    }, []);

    // Sync table width to top scrollbar
    useEffect(() => {
        const updateWidth = () => {
            if (tableContainerRef.current) {
                setTableWidth(tableContainerRef.current.scrollWidth);
            }
        };

        updateWidth();
        // Also update after a short delay for any rendering settle
        const timer = setTimeout(updateWidth, 100);

        window.addEventListener('resize', updateWidth);
        return () => {
            clearTimeout(timer);
            window.removeEventListener('resize', updateWidth);
        };
    }, [routine, metadata, overtimeVisibility, loading]);

    const handleBatchRoomUpdate = async (batchId) => {
        const loadingToast = toast.loading('Updating Default Room...');
        try {
            const batch = metadata.batches.find(b => b.id === batchId);
            if (!batch) throw new Error("Batch not found");

            await updateBatch(batchId, { ...batch, default_room_id: selectedBatchRoom || null });
            await fetchData();
            toast.success('Room updated!', { id: loadingToast });
            setEditingBatchId(null);
        } catch (err) {
            console.error("Update Error:", err);
            toast.error('Failed to update room.', { id: loadingToast });
        }
    };

    const handleAddClassClick = (day, time, batchId) => {
        const batch = metadata.batches.find(b => b.id === batchId);
        setEditingRoutineId(null);
        setNewClassData({
            day,
            time,
            batchId,
            courseId: '',
            facultyId: '',
            roomId: batch ? batch.default_room_id || '' : '',
            additional_text: ''
        });
        setIsAddModalOpen(true);
    };

    const handleEditClassClick = (classInfo, batchId) => {
        // Handle array (multiple classes in one slot)
        if (Array.isArray(classInfo)) {
            if (classInfo.length > 1) {
                setSelectionModalData({ classes: classInfo, batchId });
                return;
            }
            classInfo = classInfo[0]; // If array of 1, just take first
        }

        setEditingRoutineId(classInfo.id);
        setNewClassData({
            day: classInfo.day || '',
            time: classInfo.originalTime || '',
            batchId: batchId,
            courseId: classInfo.courseId || '',
            facultyId: classInfo.facultyId || '',
            roomId: classInfo.roomId || '',
            additional_text: classInfo.additionalText || ''
        });
        setIsAddModalOpen(true);
    };

    const handleCellClick = (currentData, batchId) => {
        if (!currentData || currentData.length === 0) return;

        // If multiple classes, handle selection
        if (currentData.length > 1) {
            setSelectionModalData({ classes: currentData, batchId, mode: 'contact' });
            return;
        }

        const batch = metadata.batches.find(b => b.id === batchId);
        
        if (batch) {
            setActiveBatchInfo({
                id: batch.id,
                name: batch.name,
                section: batch.section
            });
            
            const facultyIds = currentData.map(d => String(d.facultyId));
            const selectFaculty = metadata.faculty.filter(f => facultyIds.includes(String(f.id)));
            
            const crList = (metadata.students || []).filter(s => 
                s.batch === batch.name && 
                s.section === batch.section && 
                s.account_type === 'CR/ACR'
            );

            setSelectedFacultyList(selectFaculty);
            setSelectedCRList(crList);
            setShowContactModal(true);
        }
    };

    const getContactDefaultTab = () => {
        if (!contactSmartDefaults) return undefined;
        if (viewMode === 'section') return 'faculty';
        if (viewMode === 'faculty') return 'students';
        return undefined;
    };


    const handleSaveClass = async () => {
        if (!newClassData.courseId || !newClassData.facultyId) {
            toast.error('Please fill all fields');
            return;
        }

        const loadingToast = toast.loading(editingRoutineId ? 'Updating Class...' : 'Adding Class...');
        try {
            if (editingRoutineId) {
                await updateRoutineEntry(editingRoutineId, {
                    day: newClassData.day,
                    time: newClassData.time,
                    batch_id: newClassData.batchId,
                    course_id: newClassData.courseId,
                    faculty_id: newClassData.facultyId,
                    room_id: newClassData.roomId || null,
                    additional_text: newClassData.additional_text
                });
                toast.success('Class updated successfully!', { id: loadingToast });
            } else {
                await addRoutineEntry({
                    day: newClassData.day,
                    time: newClassData.time,
                    batch_id: newClassData.batchId,
                    course_id: newClassData.courseId,
                    faculty_id: newClassData.facultyId,
                    room_id: newClassData.roomId || null,
                    additional_text: newClassData.additional_text
                });
                toast.success('Class added successfully!', { id: loadingToast });
            }
            await fetchData();
            setIsAddModalOpen(false);
        } catch (err) {
            console.error("Save Class Error:", err);
            toast.error(editingRoutineId ? 'Failed to update class.' : 'Failed to add class.', { id: loadingToast });
        }
    };

    const handleDeleteClass = async () => {
        if (!editingRoutineId) return;
        if (!window.confirm('Are you sure you want to delete this class?')) return;

        const loadingToast = toast.loading('Deleting Class...');
        try {
            await deleteRoutineEntry(editingRoutineId);
            await fetchData();
            toast.success('Class deleted!', { id: loadingToast });
            setIsAddModalOpen(false);
        } catch (err) {
            console.error("Delete Error:", err);
            toast.error('Failed to delete class.', { id: loadingToast });
        }
    };

    // Helper functions
    const getRoomName = (id) => metadata.rooms.find(r => String(r.id) === String(id))?.room_number || 'TBA';
    const getFacultyInitials = (id) => metadata.faculty.find(f => String(f.id) === String(id))?.initials || metadata.faculty.find(f => String(f.id) === String(id))?.name?.split(' ').map(n => n[0]).join('') || 'TBA';
    const getCourseCode = (id) => {
        // Handle composite IDs like "201-401"
        const cleanId = String(id).split('-')[0];
        return metadata.courses.find(c => String(c.id) === cleanId)?.code || 'TBA';
    };
    const getCourseCredit = (id) => {
        const cleanId = String(id).split('-')[0];
        return metadata.courses.find(c => String(c.id) === cleanId)?.credit || 0;
    };

    const isLabCourse = (courseId) => {
        if (!courseId) return false;
        const cleanId = String(courseId).split('-')[0];
        const course = metadata.courses.find(c => String(c.id) === cleanId);
        if (!course) return false;

        // Priority 1: Check type explicitly
        if (course.type === 'Lab' || course.type === 'Sessional') return true;

        // Priority 2: Check for "Laboratory" or "Sessional" in name
        if (course.name.toLowerCase().includes('laboratory') || course.name.toLowerCase().includes('sessional')) return true;

        // Priority 3: Check Even ID rule
        const codeParts = course.code.split('-');
        const lastPart = codeParts[codeParts.length - 1];
        const num = parseInt(lastPart);
        if (!isNaN(num) && num % 2 === 0) return true;

        return false;
    };

    // Helper to get configuration for a specific day
    const getConfigForDay = (day) => {
        if (!scheduleSettings.daily_overrides) return scheduleSettings.general || { theory_slots: [], lab_slots: [], slot_mapping: {} };
        return scheduleSettings.daily_overrides[day] || scheduleSettings.general;
    };

    const getVisibleSlots = (day) => {
        const config = getConfigForDay(day);
        const theorySlots = config.theory_slots;
        return overtimeVisibility[day] ? theorySlots : theorySlots.slice(0, 6);
    };

    const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

    const renderTableHeader = () => (
        <thead className="text-xs uppercase bg-muted/50 text-muted-foreground">
            <tr>
                <th className="px-4 py-4 w-32 font-bold border border-border !border-r-4 !border-r-slate-300 dark:!border-r-slate-600 text-center sticky left-0 bg-secondary z-20" rowSpan={2}>
                    Batch
                </th>
                {days.map(day => (
                    <th key={day} colSpan={getVisibleSlots(day).length} className="px-4 py-2 border border-border !border-r-4 !border-r-slate-300 dark:!border-r-slate-600 text-center font-bold text-lg bg-indigo-100/50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-300 min-w-[200px]">
                        <div className="flex items-center justify-center gap-2">
                            <span>{day}</span>
                            {canEdit && (
                                <button
                                    onClick={() => setOvertimeVisibility(prev => ({ ...prev, [day]: !prev[day] }))}
                                    className={cn(
                                        "ml-2 inline-flex h-4 w-7 items-center rounded-full transition-colors focus:outline-none focus:ring-1 focus:ring-indigo-500",
                                        overtimeVisibility[day] ? "bg-indigo-600" : "bg-muted-foreground/30"
                                    )}
                                    title="Toggle Overtime"
                                >
                                    <span
                                        className={cn(
                                            "inline-block h-3 w-3 transform rounded-full bg-white transition-transform",
                                            overtimeVisibility[day] ? "translate-x-3.5" : "translate-x-0.5"
                                        )}
                                    />
                                </button>
                            )}
                        </div>
                    </th>
                ))}
            </tr>
            <tr>
                {days.map(day => (
                    <React.Fragment key={day}>
                        {getVisibleSlots(day).map((slot, index, array) => (
                            <th key={`${day}-${slot}`} className={cn(
                                "px-2 py-1 border border-border text-center min-w-[100px] whitespace-nowrap text-[10px]",
                                index === array.length - 1 && "!border-r-4 !border-r-slate-300 dark:!border-r-slate-600"
                            )}>
                                {slot}
                            </th>
                        ))}
                    </React.Fragment>
                ))}
            </tr>
        </thead>
    );

    const renderRawCell = (batchId, timeSlot, currentDay) => {
        // Find class for specific day
        const specificDayRoutine = routine.filter(r => r.day === currentDay);
        const dayConfig = getConfigForDay(currentDay);
        const labSlot = dayConfig.slot_mapping[timeSlot];

        // Filter all matching entries instead of finding just one
        const classInfos = specificDayRoutine.filter(r =>
            r.batch_id === batchId &&
            (
                r.time === timeSlot ||
                (labSlot && r.time === labSlot) ||
                r.time.replace(' ', '') === timeSlot.replace(' ', '')
            )
        );

        if (!classInfos || classInfos.length === 0) return [];

        return classInfos.map(classInfo => {
            const isLab = isLabCourse(classInfo.course_id);
            const credit = getCourseCredit(classInfo.course_id);
            return {
                id: classInfo.id,
                course: getCourseCode(classInfo.course_id),
                faculty: getFacultyInitials(classInfo.faculty_id),
                room: getRoomName(classInfo.room_id),
                courseId: classInfo.course_id,
                roomId: classInfo.room_id,
                facultyId: classInfo.faculty_id,
                additionalText: classInfo.additional_text,
                isLab: isLab,
                credit: credit,
                originalTime: classInfo.time,
                day: currentDay
            };
        });
    };

    const downloadPDF = (pdfSettings) => {
        generateWeeklyRoutinePDF(pdfSettings, metadata.faculty);
    };

    const handleExportBackup = async () => {
        const loadingToast = toast.loading('Exporting backup...');
        try {
            const response = await exportRoutine();

            // Create blob link to download
            const url = window.URL.createObjectURL(new Blob([response.data]));
            const link = document.createElement('a');
            link.href = url;

            // Generate filename: routine_backup_dd-mm-yyyy_hh-mm-ss-tt_v1.json
            const now = new Date();
            const pad = (n) => String(n).padStart(2, '0');
            const dd = pad(now.getDate());
            const mm = pad(now.getMonth() + 1);
            const yyyy = now.getFullYear();

            let hours = now.getHours();
            const tt = hours >= 12 ? 'pm' : 'am';
            hours = hours % 12 || 12; // Convert to 12-hour format
            const hh = pad(hours);
            const min = pad(now.getMinutes());
            const ss = pad(now.getSeconds());

            const formattedDate = `${dd}-${mm}-${yyyy}`;
            const formattedTime = `${hh}-${min}-${ss}-${tt}`;
            let filename = `routine_backup_${formattedDate}_${formattedTime}_v1.json`;

            link.setAttribute('download', filename);
            document.body.appendChild(link);
            link.click();
            link.parentNode.removeChild(link);

            toast.success('Backup exported successfully!', { id: loadingToast });
        } catch (error) {
            console.error("Export failed:", error);
            toast.error('Failed to export backup.', { id: loadingToast });
        }
    };

    const handleImportBackup = () => {
        if (fileInputRef.current) {
            fileInputRef.current.click();
        }
    };

    const handleSavePdfSettings = async (newSettings) => {
        setPdfSettings(newSettings);
        try {
            await updateSettings(newSettings, 'pdf_settings_week');
            toast.success("PDF settings saved globally!");
        } catch (error) {
            console.error("Failed to save PDF settings", error);
            toast.error("Failed to save PDF settings to server. Saving locally only.");
            localStorage.setItem('nwu_routine_pdf_settings', JSON.stringify(newSettings));
        }
    };

    const processFileImport = async (event) => {
        const file = event.target.files[0];
        if (!file) return;

        // Reset the input so the same file can be selected again if needed
        event.target.value = null;

        if (!window.confirm('This will completely replace the current routine logic with the imported backup. Are you sure?')) {
            return;
        }

        const reader = new FileReader();
        reader.onload = async (e) => {
            const loadingToast = toast.loading('Restoring backup...');
            try {
                const jsonContent = JSON.parse(e.target.result);

                await importRoutine(jsonContent);
                toast.success('Backup restored successfully!', { id: loadingToast });

                // Refresh data to show restored routine
                fetchData();
            } catch (error) {
                console.error("Import failed:", error);
                toast.error(error.response?.data?.message || 'Failed to restore backup.', { id: loadingToast });
            }
        };

        reader.onerror = () => {
            toast.error('Failed to read the file.');
        };

        reader.readAsText(file);
    };

    const handleClearRoutine = async () => {
        const confirmation = window.prompt('To clear the FULL routine data, please type "clear full routine":');
        if (confirmation !== 'clear full routine') {
            if (confirmation !== null) {
                toast.error('Invalid confirmation message. Routine not cleared.');
            }
            return;
        }

        const loadingToast = toast.loading('Clearing full routine...');
        try {
            await clearRoutine();
            toast.success('Full routine data cleared successfully!', { id: loadingToast });
            fetchData();
        } catch (err) {
            console.error("Clear Routine Error:", err);
            toast.error(err.response?.data?.message || 'Failed to clear routine.', { id: loadingToast });
        }
    };

    // Determine active time slots based on selected course and day in add modal
    const modalDayConfig = getConfigForDay(newClassData.day);
    const theorySlots = modalDayConfig.theory_slots;
    const labSlots = modalDayConfig.lab_slots;
    const activeTimeSlots = isLabCourse(newClassData.courseId) ? labSlots : theorySlots;

    return (
        <div className="space-y-6 flex flex-col max-w-[100vw] px-4 relative">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h2 className="text-3xl font-bold tracking-tight text-foreground">Weekly Schedule</h2>
                    <p className="text-muted-foreground mt-1">Full Week Overview</p>
                </div>

                <div className="flex flex-wrap gap-2 items-center">
                    {canEdit && (
                        <>
                            <div className="flex bg-muted/30 p-1 rounded-md border border-border">
                                <input
                                    type="file"
                                    ref={fileInputRef}
                                    className="hidden"
                                    accept=".json"
                                    onChange={processFileImport}
                                />
                                <Button variant="ghost" size="sm" onClick={() => setIsCloudModalOpen(true)} title="Cloud Backup" className="text-muted-foreground hover:text-blue-600">
                                    <Cloud className="mr-2 h-4 w-4" />
                                    Cloud
                                </Button>
                                <Button variant="ghost" size="sm" onClick={handleExportBackup} title="Local Backup" className="text-muted-foreground hover:text-indigo-600">
                                    <HardDriveDownload className="mr-2 h-4 w-4" />
                                    Local
                                </Button>
                                <Button variant="ghost" size="sm" onClick={handleImportBackup} title="Restore Routine" className="text-muted-foreground hover:text-emerald-600">
                                    <Upload className="mr-2 h-4 w-4" />
                                    Restore
                                </Button>
                                <Button variant="ghost" size="sm" onClick={handleClearRoutine} title="Clear Full Routine" className="text-muted-foreground hover:text-red-500">
                                    <Trash2 className="mr-2 h-4 w-4" />
                                    Clear
                                </Button>
                            </div>
                            <Button variant="outline" onClick={() => setShowSettingsModal(true)}>
                                <Settings className="mr-2 h-4 w-4" />
                                Settings
                            </Button>
                        </>
                    )}
                    <div className="flex bg-muted/30 p-1 rounded-md border border-border">
                        {user && canEdit && (
                            <Button variant="ghost" size="sm" onClick={() => setIsPdfModalOpen(true)} title="PDF Settings" className="text-muted-foreground hover:text-indigo-600 border-r border-border rounded-r-none pr-3">
                                <Settings2 className="h-4 w-4" />
                            </Button>
                        )}
                        <Button
                            variant="default"
                            className={cn(
                                "bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm",
                                user && canEdit ? "rounded-l-none" : ""
                            )}
                            onClick={() => downloadPDF(pdfSettings)}
                        >
                            <Download className="mr-2 h-4 w-4" />
                            PDF
                        </Button>
                    </div>
                </div>
            </div>

            {/* Sticky Duplicate Header */}
            {showStickyHeader && (
                <div
                    className="fixed top-[64px] z-40 bg-card border-b border-border shadow-md pointer-events-auto table-container-wrapper"
                    style={{ left: headerLayout.left, width: headerLayout.width }}
                >
                    <div
                        className="overflow-x-auto table-scroll-area"
                        ref={duplicateHeaderRef}
                        style={{ width: '100%' }}
                    >
                        <table className="w-full text-sm text-left border-collapse" style={{ width: tableWidth }}>
                            {renderTableHeader()}
                        </table>
                    </div>
                </div>
            )}

            <div className="bg-card rounded-lg border border-border shadow-sm table-container-wrapper">
                {/* Top Scrollbar */}
                <div
                    ref={topScrollContainerRef}
                    className="overflow-x-auto border-b border-border bg-muted/10 table-scroll-area"
                    style={{ height: '16px' }}
                >
                    <div style={{ width: tableWidth, height: '1px' }}></div>
                </div>

                <div className="overflow-x-auto table-scroll-area" ref={tableContainerRef}>
                    <table id="week-routine-table" className="w-full text-sm text-left border-collapse">
                        {renderTableHeader()}
                        <tbody className="divide-y divide-border">
                            {sortedBatches.map(batch => (
                                <tr key={batch.id} className="hover:bg-muted/10">
                                    <td className="px-4 py-3 font-semibold text-foreground border border-border !border-r-4 !border-r-slate-300 dark:!border-r-slate-600 sticky left-0 bg-card z-10 whitespace-nowrap min-w-[150px]">
                                        <div className="text-xs text-muted-foreground">{batch.name}</div>
                                        <div className="font-bold text-indigo-600 dark:text-indigo-400">Section {batch.section}</div>
                                        <div
                                            className={cn(
                                                "mt-1 flex items-center gap-1 text-[10px] text-muted-foreground px-1.5 py-0.5 rounded w-fit transition-colors",
                                                canEdit ? "bg-muted/50 cursor-pointer hover:bg-indigo-100 hover:text-indigo-700" : ""
                                            )}
                                            onClick={() => {
                                                if (!canEdit) return;
                                                setEditingBatchId(batch.id);
                                                setSelectedBatchRoom(batch.default_room_id || '');
                                            }}
                                            title="Edit Default Room"
                                        >
                                            <MapPin className="w-3 h-3" />
                                            {editingBatchId === batch.id ? (
                                                <div className="flex items-center gap-1" onClick={e => e.stopPropagation()}>
                                                    <select
                                                        className="h-5 text-[10px] bg-background border rounded"
                                                        value={selectedBatchRoom}
                                                        onChange={(e) => setSelectedBatchRoom(e.target.value)}
                                                    >
                                                        <option value="">Select</option>
                                                        {sortedRooms.map(r => (
                                                            <option key={r.id} value={r.id}>{r.room_number}</option>
                                                        ))}
                                                    </select>
                                                    <Check
                                                        className="w-3 h-3 text-emerald-600 cursor-pointer hover:scale-110"
                                                        onClick={() => handleBatchRoomUpdate(batch.id)}
                                                    />
                                                    <X
                                                        className="w-3 h-3 text-red-500 cursor-pointer hover:scale-110"
                                                        onClick={() => setEditingBatchId(null)}
                                                    />
                                                </div>
                                            ) : (
                                                getRoomName(batch.default_room_id) !== 'TBA' && (
                                                    <span>Room: {getRoomName(batch.default_room_id)}</span>
                                                )
                                            )}
                                        </div>
                                    </td>

                                    {days.map(day => {
                                        const cells = [];
                                        let i = 0;
                                        const currentTheorySlots = getVisibleSlots(day);
                                        while (i < currentTheorySlots.length) {
                                            const currentSlot = currentTheorySlots[i];
                                            const currentData = renderRawCell(batch.id, currentSlot, day);
                                            let colSpan = 1;

                                            if (currentData && currentData.length > 0) {
                                                const dayConfig = getConfigForDay(day);
                                                const currentDayLabSlots = dayConfig.lab_slots;
                                                // Use the first entry to determine colspan (assuming aligned slots)
                                                const firstEntry = currentData[0];
                                                if (firstEntry.isLab && currentDayLabSlots.includes(firstEntry.originalTime)) {
                                                    const labEndTimeStr = firstEntry.originalTime.split('-')[1].trim();
                                                    const endSlotIndex = currentTheorySlots.findIndex(s => s.endsWith(labEndTimeStr));
                                                    if (endSlotIndex !== -1 && endSlotIndex >= i) {
                                                        colSpan = (endSlotIndex - i) + 1;
                                                    } else {
                                                        colSpan = 2; // Fallback
                                                    }
                                                }
                                            }

                                            // Safety check for colSpan extending beyond visible columns
                                            if (i + colSpan > currentTheorySlots.length) {
                                                colSpan = currentTheorySlots.length - i;
                                            }

                                            // Prepare display data directly
                                            const displayCourses = currentData.map(d => d.isLab ? `${d.course}` : d.course).join(' / ');
                                            const displayFaculty = currentData.map(d => d.faculty).join(' / ');
                                            const displayRoom = currentData.map(d => d.room).join(' / ');
                                            const displayAdditionalText = currentData.map(d => d.additionalText).filter(Boolean).join(' / ');
                                            const isLab = currentData.some(d => d.isLab);
                                            const isAlt = currentData.some(d => d.credit === 0.75 || d.credit === "0.75");
                                            const canAddSecond = currentData.length === 1 && isAlt;

                                            cells.push(
                                                <td key={currentSlot} colSpan={colSpan} className={cn(
                                                    "px-1 py-1 border border-border text-center align-middle h-24 relative group min-w-[100px]",
                                                    (i + colSpan) >= currentTheorySlots.length && "!border-r-4 !border-r-slate-300 dark:!border-r-slate-600"
                                                )}>
                                                    {currentData.length > 0 ? (
                                                        <div
                                                            className={cn(
                                                                "flex flex-col items-center justify-center space-y-0.5 p-1 rounded-sm transition-colors h-full w-full relative group",
                                                                "cursor-pointer hover:bg-muted/50"
                                                            )}
                                                            onClick={() => handleCellClick(currentData, batch.id)}
                                                        >
                                                            <span className="font-bold text-foreground text-[10px] leading-[1.1]">{displayCourses}</span>
                                                            <span className="text-[9px] text-muted-foreground bg-muted px-1 py-0 rounded">
                                                                {displayFaculty}
                                                            </span>
                                                            {displayRoom && displayRoom !== 'TBA' && (
                                                                <span className="text-[9px] font-mono text-indigo-500 font-medium">
                                                                    R-{displayRoom}
                                                                </span>
                                                            )}
                                                            <div className="flex gap-1">
                                                                {isLab && (
                                                                    <span className="text-[8px] text-emerald-600 font-bold uppercase tracking-wider">
                                                                        <span className="hidden">PDF_LAB </span>LAB
                                                                    </span>
                                                                )}
                                                                {isAlt && (
                                                                    <span className="text-[8px] text-orange-600 font-bold uppercase tracking-wider">
                                                                        <span className="hidden">PDF_ALT </span>ALT
                                                                    </span>
                                                                )}
                                                            </div>
                                                            {displayAdditionalText && (
                                                                <span className="text-[9px] text-emerald-600 font-medium leading-tight">
                                                                    <span className="hidden">EXTRA_TEXT: </span>{displayAdditionalText}
                                                                </span>
                                                            )}

                                                            {/* Hover Hint / Edit Overlay */}
                                                            {canEdit && (
                                                                <span className="absolute top-0.5 right-0.5 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1">
                                                                    {/* If can add second, show Plus here too or just Edit? User asked for optional add. */}
                                                                    {canAddSecond && (
                                                                        <Button
                                                                            variant="ghost"
                                                                            size="icon"
                                                                            className="h-4 w-4 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-100 rounded-full"
                                                                            onClick={(e) => {
                                                                                e.stopPropagation();
                                                                                handleAddClassClick(day, currentSlot, batch.id); // Add to same slot
                                                                            }}
                                                                            title="Add Alternate Lab"
                                                                        >
                                                                            <Plus className="h-3 w-3" />
                                                                        </Button>
                                                                    )}
                                                                    <Edit2
                                                                        className="h-4 w-4 text-muted-foreground hover:text-indigo-600 cursor-pointer p-0.5"
                                                                        onClick={(e) => {
                                                                            e.stopPropagation();
                                                                            handleEditClassClick(currentData, batch.id);
                                                                        }}
                                                                    />
                                                                </span>
                                                            )}
                                                        </div>
                                                    ) : (
                                                        canEdit && (
                                                            <div
                                                                className="flex items-center justify-center w-full h-full opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer hover:bg-muted/50 rounded-sm"
                                                                onClick={() => handleAddClassClick(day, currentSlot, batch.id)}
                                                                title="Add Class"
                                                            >
                                                                <Plus className="h-4 w-4 text-muted-foreground/50 hover:text-indigo-500" />
                                                            </div>
                                                        )
                                                    )}
                                                </td>
                                            );
                                            i += colSpan;
                                        }
                                        return cells;
                                    })}
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            <UnifiedContactModal
                isOpen={showContactModal}
                onClose={() => setShowContactModal(false)}
                facultyList={selectedFacultyList}
                studentList={selectedCRList}
                batchName={activeBatchInfo.name}
                sectionName={activeBatchInfo.section}
                defaultTab={getContactDefaultTab()}
            />

            {/* Add Class Modal */}
            {
                isAddModalOpen && (() => {
                    const selectedBatch = metadata.batches.find(b => String(b.id) === String(newClassData.batchId));
                    let filteredCourses = metadata.courses;

                    if (selectedBatch) {
                        const parts = selectedBatch.name.split(' ');
                        const yearNum = parseInt(parts[0]) || 0;
                        const semNum = parts.length >= 3 ? parseInt(parts[2]) : 0;

                        if (yearNum && semNum) {
                            const prefix = `${yearNum}${semNum}`;
                            const filtered = metadata.courses.filter(c => {
                                const numericPart = c.code.match(/\d+/);
                                return numericPart && numericPart[0].startsWith(prefix);
                            });
                            if (filtered.length > 0) filteredCourses = filtered;
                        }
                    }

                    return (
                        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
                            <div className="bg-card w-full max-w-md rounded-lg shadow-lg border border-border p-6 space-y-4">
                                <div className="flex justify-between items-center">
                                    <h3 className="text-lg font-semibold flex items-center gap-2">
                                        {editingRoutineId ? (
                                            <>
                                                <Edit2 className="h-4 w-4 text-indigo-500" />
                                                Edit Class Details
                                            </>
                                        ) : (
                                            <>
                                                <Plus className="h-4 w-4 text-emerald-500" />
                                                Add Manual Class
                                            </>
                                        )}
                                    </h3>
                                    <Button variant="ghost" size="icon" onClick={() => setIsAddModalOpen(false)}>
                                        <X className="h-4 w-4" />
                                    </Button>
                                </div>
                                <div className="space-y-3">
                                    <div className="grid grid-cols-2 gap-3 text-sm">
                                        <div>
                                            <label className="block text-muted-foreground mb-1">Day</label>
                                            <div className="font-medium p-2 bg-muted rounded border">{newClassData.day}</div>
                                        </div>
                                        <div>
                                            <label className="block text-sm font-medium mb-1">
                                                Time Slot
                                                {isLabCourse(newClassData.courseId) && <span className="text-xs text-emerald-600 ml-2">(Lab Duration)</span>}
                                            </label>
                                            <select
                                                className="w-full p-2 rounded-md border border-input bg-background text-sm"
                                                value={newClassData.time}
                                                onChange={(e) => setNewClassData({ ...newClassData, time: e.target.value })}
                                            >
                                                <option value="">Select Time</option>
                                                {activeTimeSlots.map(t => <option key={t} value={t}>{t}</option>)}
                                            </select>
                                        </div>
                                    </div>

                                    {/* Smart Defaults Toggle */}
                                    {(viewMode === 'section' || viewMode === 'faculty') && (
                                        <div className="flex items-center gap-2 px-3 border-l border-border ml-2">
                                            <span className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground whitespace-nowrap hidden lg:inline">Smart Contacts:</span>
                                            <button
                                                onClick={() => setContactSmartDefaults(!contactSmartDefaults)}
                                                className={cn(
                                                    "relative inline-flex h-5 w-9 items-center rounded-full transition-colors focus:outline-none focus:ring-1 focus:ring-indigo-500",
                                                    contactSmartDefaults ? "bg-emerald-500" : "bg-muted-foreground/30"
                                                )}
                                                title="Toggle automatic tab selection for Section/Faculty views"
                                            >
                                                <span
                                                    className={cn(
                                                        "inline-block h-3.5 w-3.5 transform rounded-full bg-white transition-transform",
                                                        contactSmartDefaults ? "translate-x-4" : "translate-x-0.5"
                                                    )}
                                                />
                                            </button>
                                        </div>
                                    )}
                                    <div>
                                        <label className="block text-sm font-medium mb-1">Course</label>
                                        <select
                                            className="w-full p-2 rounded-md border border-input bg-background text-sm"
                                            value={newClassData.courseId}
                                            onChange={(e) => {
                                                const newCourseId = e.target.value;
                                                let newTime = newClassData.time;

                                                // Intelligent Time Slot Mapping
                                                if (newCourseId && newClassData.time) {
                                                    const isLab = isLabCourse(newCourseId);
                                                    // Case 1: Switching to Lab Course
                                                    if (isLab) {
                                                        // Try to find a lab slot that starts at the same time
                                                        const theoryStart = newClassData.time.split('-')[0].trim();
                                                        const matchingLabSlot = labSlots.find(ls => ls.startsWith(theoryStart));

                                                        if (matchingLabSlot) {
                                                            newTime = matchingLabSlot;
                                                        } else if (!labSlots.includes(newClassData.time)) {
                                                            // If current time isn't a valid lab slot and no match found, reset or keep? 
                                                            // RoutineView resets to '' if no match found.
                                                            newTime = '';
                                                        }
                                                    }
                                                    // Case 2: Switching to Theory Course
                                                    else {
                                                        // If currently selected time is a Lab slot (longer), try to revert to standard slot
                                                        if (labSlots.includes(newClassData.time)) {
                                                            const labStart = newClassData.time.split('-')[0].trim();
                                                            const matchingTheorySlot = theorySlots.find(ts => ts.startsWith(labStart));
                                                            if (matchingTheorySlot) {
                                                                newTime = matchingTheorySlot;
                                                            } else {
                                                                newTime = '';
                                                            }
                                                        }
                                                    }
                                                }
                                                setNewClassData({ ...newClassData, courseId: newCourseId, time: newTime });
                                            }}
                                        >
                                            <option value="">Select Course</option>
                                            {[...filteredCourses]
                                                .sort((a, b) => {
                                                    const aNum = parseInt(a.code.match(/\d+/)?.[0] || 0);
                                                    const bNum = parseInt(b.code.match(/\d+/)?.[0] || 0);
                                                    return aNum - bNum || a.code.localeCompare(b.code);
                                                })
                                                .map(course => (
                                                    <option key={course.id} value={course.id}>{course.code} - {course.name}</option>
                                                ))
                                            }
                                        </select>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium mb-1">Faculty</label>
                                        <SearchableSelect
                                            options={metadata.faculty
                                                .sort((a, b) => a.name.localeCompare(b.name))
                                                .map(f => ({
                                                    value: f.id,
                                                    label: `${f.name} (${f.initials})`,
                                                    searchTerms: `${f.name} ${f.initials}`
                                                }))
                                            }
                                            value={newClassData.facultyId}
                                            onValueChange={(val) => setNewClassData({ ...newClassData, facultyId: val })}
                                            placeholder="Select Faculty"
                                            searchPlaceholder="Search name or initials..."
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium mb-1">Room</label>
                                        <SearchableSelect
                                            options={[
                                                { value: '', label: 'None / TBA' },
                                                ...metadata.rooms.filter(room => {
                                                    if (!newClassData.courseId) return true;
                                                    const courseId = String(newClassData.courseId).split("-")[0];
                                                    const course = metadata.courses.find(c => String(c.id) === courseId);
                                                    if (!course) return true;
                                                    if (course.code === "HUM-1142" || course.code === "Hum-1142") return true;
                                                    const isLab = isLabCourse(newClassData.courseId);
                                                    return isLab ? room.type === "Lab" : room.type === "Theory";
                                                })
                                                    .sort((a, b) => {
                                                        const aNum = parseInt(a.room_number.match(/\d+/)?.[0] || 0);
                                                        const bNum = parseInt(b.room_number.match(/\d+/)?.[0] || 0);
                                                        return aNum - bNum || a.room_number.localeCompare(b.room_number);
                                                    })
                                                    .map(room => ({
                                                        value: room.id,
                                                        label: `${room.room_number} (${room.type === "Theory" ? "Class" : "Laboratory"})`,
                                                        searchTerms: room.room_number
                                                    }))
                                            ]}
                                            value={newClassData.roomId}
                                            onValueChange={(val) => setNewClassData({ ...newClassData, roomId: val })}
                                            placeholder="Select Room"
                                            searchPlaceholder="Search room number..."
                                        />
                                    </div>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium mb-1">Add additional text (optional)</label>
                                    <input
                                        type="text"
                                        className="w-full p-2 rounded-md border border-input bg-background text-sm"
                                        value={newClassData.additional_text || ''}
                                        onChange={(e) => setNewClassData({ ...newClassData, additional_text: e.target.value })}
                                        placeholder="E.g. Makeup class, Alternate faculty..."
                                    />
                                </div>
                                <div className="flex justify-between gap-2 pt-2">
                                    {editingRoutineId ? (
                                        <Button variant="destructive" size="sm" onClick={handleDeleteClass}>
                                            <Trash className="w-4 h-4 mr-2" />
                                            Delete
                                        </Button>
                                    ) : <div></div>}
                                    <div className="flex gap-2">
                                        <Button variant="outline" onClick={() => setIsAddModalOpen(false)}>Cancel</Button>
                                        <Button onClick={handleSaveClass}>{editingRoutineId ? 'Update Class' : 'Save Class'}</Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    );
                })()}

            {/* Selection Modal for Multi-Class Slots */}
            <SelectionModal
                isOpen={!!selectionModalData}
                onClose={() => setSelectionModalData(null)}
                classes={selectionModalData?.classes || []}
                onSelect={(cls) => {
                    const mode = selectionModalData.mode;
                    const bId = selectionModalData.batchId;
                    setSelectionModalData(null);
                    if (mode === 'contact') {
                        handleCellClick([cls], bId);
                    } else {
                        handleEditClassClick([cls], bId);
                    }
                }}
            />

            {/* Settings Modal */}
            <SettingsModal
                isOpen={showSettingsModal}
                onClose={() => setShowSettingsModal(false)}
                onSettingsUpdated={(newSettings) => setScheduleSettings(newSettings)}
            />

            {/* PDF Customization Modal */}
            <PdfDownloadModal
                isOpen={isPdfModalOpen}
                onClose={() => setIsPdfModalOpen(false)}
                initialSettings={pdfSettings}
                onSave={handleSavePdfSettings}
            />

            <CloudRoutineBackupModal
                isOpen={isCloudModalOpen}
                onClose={() => setIsCloudModalOpen(false)}
                routineData={routine}
                onRestore={async (data) => {
                    const loadingToast = toast.loading('Restoring cloud backup...');
                    try {
                        await importRoutine(data);
                        toast.success('Backup restored successfully!', { id: loadingToast });
                        fetchData();
                        setIsCloudModalOpen(false);
                    } catch (error) {
                        console.error("Import failed:", error);
                        toast.error(error?.response?.data?.message || 'Failed to restore cloud backup.', { id: loadingToast });
                    }
                }}
            />
        </div>
    );
};

export default WeekRoutineView;
